import PaletteRoundedIcon from '@mui/icons-material/PaletteRounded';
import RuleRoundedIcon from '@mui/icons-material/RuleRounded';
import { Alert, Button, CircularProgress, Skeleton, Switch, TextField } from '@mui/material';
import { useEffect, useState } from 'react';
import FileUpload from '../../components/storage/FileUpload';
import { api } from '../../lib/api';

type School = { name:string; logoUrl?:string|null; description?:string|null; phone?:string|null; email?:string|null; address?:string|null; timezone:string; primaryColor:string; secondaryColor:string };
type Policy = { actionKey:string; requiresApproval:boolean; allowedForStaff:boolean };

export default function PrincipalSettings(){
  const [school,setSchool]=useState<School|null>(null); const [policies,setPolicies]=useState<Policy[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const load=async()=>{setLoading(true);try{const [{data:o},{data:p}]=await Promise.all([api.get('/school-operations/overview'),api.get<Policy[]>('/policies')]);setSchool(o.school);setPolicies(p);}catch{setError('Could not load school settings.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const saveSchool=async()=>{if(!school)return;setSaving(true);setError('');try{const {data}=await api.patch('/school-operations/school',school);setSchool(data);setMessage('School branding updated.');}catch(e:any){setError(e?.response?.data?.message??'Could not save school settings.');}finally{setSaving(false);}};
  const updatePolicy=async(p:Policy,patch:Partial<Policy>)=>{const next={...p,...patch};setPolicies(items=>items.map(i=>i.actionKey===p.actionKey?next:i));try{await api.put('/policies',next);}catch{setPolicies(items=>items.map(i=>i.actionKey===p.actionKey?p:i));setError('Could not update approval policy.');}};
  if(loading)return <div className="min-h-screen bg-[#f8fbff] p-6"><div className="mx-auto max-w-5xl space-y-4">{Array.from({length:5}).map((_,i)=><Skeleton key={i} variant="rounded" height={120} sx={{borderRadius:5}} />)}</div></div>;
  if(!school)return null;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eef5ff,#fff_50%,#fff8ed)] px-4 py-6 sm:px-8"><div className="mx-auto max-w-5xl">
    <header className="mb-7"><span className="text-xs font-black uppercase tracking-[.22em] text-violet-600">School configuration</span><h1 className="mt-2 text-3xl font-black text-slate-950 sm:text-4xl">Branding & approval rules</h1><p className="mt-2 text-sm text-slate-500">Control how your school appears and which Staff actions need Principal approval.</p></header>
    {error&&<Alert severity="error" className="mb-4" onClose={()=>setError('')}>{error}</Alert>}{message&&<Alert severity="success" className="mb-4" onClose={()=>setMessage('')}>{message}</Alert>}
    <section className="glass-panel rounded-[30px] p-5 md:p-7 mb-6"><div className="mb-5 flex items-center gap-3"><div className="rounded-2xl bg-gradient-to-br from-blue-500 to-violet-500 p-3 text-white"><PaletteRoundedIcon/></div><div><h2 className="text-xl font-black text-slate-950">School identity</h2><p className="text-sm text-slate-500">Shown under Principal, Staff, Teacher, Student and Parent accounts.</p></div></div>
      <div className="grid gap-4 sm:grid-cols-2"><TextField label="School name" value={school.name} onChange={e=>setSchool({...school,name:e.target.value})}/><div className="rounded-2xl border border-slate-200 bg-white p-3"><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-400">School logo</p><FileUpload value={school.logoUrl??''} onChange={reference=>setSchool({...school,logoUrl:reference||null})} category="school-logo" label="Upload logo" accept=".jpg,.jpeg,.png,.webp,.gif"/></div><TextField label="Email" value={school.email??''} onChange={e=>setSchool({...school,email:e.target.value})}/><TextField label="Phone" value={school.phone??''} onChange={e=>setSchool({...school,phone:e.target.value})}/><TextField label="Address" value={school.address??''} onChange={e=>setSchool({...school,address:e.target.value})}/><TextField label="Timezone" value={school.timezone} onChange={e=>setSchool({...school,timezone:e.target.value})}/><TextField label="Primary color" value={school.primaryColor} onChange={e=>setSchool({...school,primaryColor:e.target.value})}/><TextField label="Secondary color" value={school.secondaryColor} onChange={e=>setSchool({...school,secondaryColor:e.target.value})}/><TextField className="sm:col-span-2" multiline minRows={3} label="School description" value={school.description??''} onChange={e=>setSchool({...school,description:e.target.value})}/></div>
      <div className="mt-5 flex items-center gap-4"><div className="h-14 w-14 rounded-2xl border border-white shadow" style={{background:`linear-gradient(135deg,${school.primaryColor},${school.secondaryColor})`}}/><div className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-500">{school.logoUrl?'Logo securely stored':'No logo uploaded'}</div><Button variant="contained" onClick={()=>void saveSchool()} disabled={saving} sx={{ml:'auto',borderRadius:3,fontWeight:900,background:`linear-gradient(90deg,${school.primaryColor},${school.secondaryColor})`}}>{saving?<CircularProgress size={20} color="inherit"/>:'Save branding'}</Button></div>
    </section>
    <section className="glass-panel rounded-[30px] p-5 md:p-7"><div className="mb-5 flex items-center gap-3"><div className="rounded-2xl bg-gradient-to-br from-amber-400 to-rose-500 p-3 text-white"><RuleRoundedIcon/></div><div><h2 className="text-xl font-black text-slate-950">Staff approval policy</h2><p className="text-sm text-slate-500">Decide what Staff may do and whether Principal review is required.</p></div></div>
      <div className="space-y-3">{policies.map(p=><div key={p.actionKey} className="flex flex-col gap-3 rounded-[22px] border border-white bg-white/75 p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-slate-900">{p.actionKey.replaceAll('_',' ')}</p><p className="text-xs text-slate-400">Configure Staff access for this action.</p></div><div className="flex items-center gap-5 text-xs font-bold text-slate-600"><label className="flex items-center gap-2"><Switch checked={p.allowedForStaff} onChange={e=>void updatePolicy(p,{allowedForStaff:e.target.checked})}/>Staff allowed</label><label className="flex items-center gap-2"><Switch checked={p.requiresApproval} disabled={!p.allowedForStaff} onChange={e=>void updatePolicy(p,{requiresApproval:e.target.checked})}/>Needs approval</label></div></div>)}</div>
    </section>
  </div></main>;
}
