import { AssessmentRounded, CalendarMonthRounded, EmojiEventsRounded, PrintRounded, SchoolRounded } from '@mui/icons-material';
import { Alert, Button, MenuItem, Skeleton, TextField } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';

type Term={id:string;name:string;academicYear:string;startsAt:string;endsAt:string;isCurrent:boolean};
type Report={term:Term;student:{id:string;admissionNo:string;name:string;class?:{name:string;section?:string|null}|null};attendance:{rate:number;present:number;total:number};overall:{earned:number;total:number;percentage:number;grade:string};subjects:Array<{subjectId:string;subject:string;examEarned:number;examTotal:number;assignmentEarned:number;assignmentTotal:number;earned:number;total:number;percentage:number;grade:string}>};

export default function ReportCardPage(){
 const [terms,setTerms]=useState<Term[]>([]),[termId,setTermId]=useState(''),[report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const params=useMemo(()=>new URLSearchParams(location.search),[]); const studentId=params.get('studentId');
 useEffect(()=>{api.get('/reports/terms').then(({data})=>{setTerms(data);const t=data.find((x:Term)=>x.isCurrent)??data[0];if(t)setTermId(t.id);}).catch(()=>setError('Could not load academic terms.'));},[]);
 useEffect(()=>{if(!termId)return;setLoading(true);setError('');api.get('/reports/report-card',{params:{termId,studentId:studentId||undefined}}).then(({data})=>setReport(data)).catch((e:any)=>setError(e?.response?.data?.message??'Could not build report card.')).finally(()=>setLoading(false));},[termId,studentId]);
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eaf2ff,transparent_35%),radial-gradient(circle_at_top_right,#fff0e8,transparent_30%),#f8faff] p-4 md:p-8 text-slate-800 print:bg-white print:p-0"><section className="mx-auto max-w-6xl">
  <header className="rounded-[32px] border border-white bg-white/80 p-6 shadow-[0_30px_90px_rgba(70,90,140,.13)] backdrop-blur-xl print:rounded-none print:border-0 print:shadow-none"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-black uppercase tracking-[.2em] text-indigo-600 text-xs">Academic intelligence</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Report Card</h1><p className="mt-2 text-slate-500">Live results from exams, assignments and attendance.</p></div><div className="flex flex-wrap items-center gap-3 print:hidden"><TextField select label="Academic term" value={termId} onChange={e=>setTermId(e.target.value)} sx={{minWidth:220}}>{terms.map(t=><MenuItem key={t.id} value={t.id}>{t.name} · {t.academicYear}</MenuItem>)}</TextField><Button variant="contained" startIcon={<PrintRounded/>} onClick={()=>window.print()} sx={{borderRadius:3,px:2.5,py:1.4,fontWeight:900,background:'linear-gradient(90deg,#2563eb,#7c3aed)'}}>Print / Save PDF</Button></div></div></header>
  {error&&<Alert severity="error" className="mt-5">{error}</Alert>}
  {loading?<div className="mt-6 grid gap-4">{[1,2,3,4].map(x=><Skeleton key={x} height={110} variant="rounded" sx={{borderRadius:5}}/>)}</div>:report&&<>
   <section className="mt-6 grid gap-4 md:grid-cols-4 print:grid-cols-4">{[[report.student.name,report.student.class?`${report.student.class.name}${report.student.class.section?` - ${report.student.class.section}`:''}`:'No class',SchoolRounded],['Overall',`${report.overall.percentage}% · ${report.overall.grade}`,EmojiEventsRounded],['Attendance',`${report.attendance.rate}%`,CalendarMonthRounded],['Marks',`${report.overall.earned.toFixed(1)} / ${report.overall.total.toFixed(1)}`,AssessmentRounded]].map(([a,b,Icon]:any)=><article key={a} className="rounded-[26px] border border-white bg-white/85 p-5 shadow-xl transition hover:-translate-y-1 print:rounded-none print:border-slate-200 print:shadow-none"><div className="inline-flex rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-500 p-3 text-white print:hidden"><Icon/></div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">{a}</p><p className="mt-1 text-xl font-black">{b}</p></article>)}</section>
   <section className="mt-6 overflow-hidden rounded-[30px] border border-white bg-white/85 shadow-xl print:rounded-none print:border-slate-200 print:shadow-none"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-black">Subject performance</h2><p className="text-sm text-slate-500">Exam and coursework marks combined for {report.term.name}.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Subject</th><th className="p-4">Exams</th><th className="p-4">Assignments</th><th className="p-4">Total</th><th className="p-4">%</th><th className="p-4">Grade</th></tr></thead><tbody>{report.subjects.map(s=><tr key={s.subjectId} className="border-t border-slate-100"><td className="p-4 font-black">{s.subject}</td><td className="p-4">{s.examEarned.toFixed(1)} / {s.examTotal.toFixed(1)}</td><td className="p-4">{s.assignmentEarned.toFixed(1)} / {s.assignmentTotal.toFixed(1)}</td><td className="p-4 font-bold">{s.earned.toFixed(1)} / {s.total.toFixed(1)}</td><td className="p-4"><span className="rounded-full bg-indigo-50 px-3 py-1 font-black text-indigo-700">{s.percentage}%</span></td><td className="p-4 text-lg font-black">{s.grade}</td></tr>)}</tbody></table></div></section>
   <footer className="mt-8 hidden grid-cols-2 gap-16 pt-12 text-sm print:grid"><div className="border-t border-slate-400 pt-2 text-center">Class Teacher Signature</div><div className="border-t border-slate-400 pt-2 text-center">Principal Signature</div></footer>
  </>}
 </section></main>;
}
