import AddChartRoundedIcon from "@mui/icons-material/AssessmentRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { Alert, Button, CircularProgress, MenuItem, Skeleton, TextField } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../../features/auth/AuthProvider";
import { api } from "../../lib/api";

type Directory = { classes: Array<{ id: string; name: string; section?: string | null }>; subjects: Array<{ id: string; name: string }> };
type Student = { id: string; firstName: string; lastName: string; admissionNo: string };
type Result = { id: string; correctAnswers: number; score: number | string; questionMarks: number[]; remarks?: string | null; student: Student };
type Test = { id: string; title: string; testType: "WEEKLY" | "MONTHLY"; heldAt: string; questionCount: number; marksPerQuestion: number | string; totalMarks: number | string; class: { id: string; name: string; section?: string | null }; subject: { id: string; name: string }; createdBy: { firstName: string; lastName: string }; results: Result[] };

const today = () => new Date().toISOString().slice(0, 10);
export default function ManualTestsPage() {
  const { user } = useAuth(), manager = user?.role === "TEACHER" || user?.role === "PRINCIPAL";
  const [tests, setTests] = useState<Test[]>([]), [directory, setDirectory] = useState<Directory>({ classes: [], subjects: [] }), [roster, setRoster] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true), [rosterLoading, setRosterLoading] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [editingId, setEditingId] = useState(""), [classId, setClassId] = useState(""), [subjectId, setSubjectId] = useState(""), [title, setTitle] = useState(""), [testType, setTestType] = useState<"WEEKLY" | "MONTHLY">("WEEKLY"), [heldAt, setHeldAt] = useState(today()), [questionCount, setQuestionCount] = useState(5), [marksPerQuestion, setMarksPerQuestion] = useState(5), [marks, setMarks] = useState<Record<string, number[]>>({}), [remarks, setRemarks] = useState<Record<string, string>>({});
  const load = async () => { setLoading(true); setError(""); try { const requests: Promise<any>[] = [api.get("/manual-tests")]; if (manager) requests.push(api.get("/school-directory")); const [testResponse, directoryResponse] = await Promise.all(requests); setTests(testResponse.data); if (directoryResponse) { setDirectory(directoryResponse.data); setClassId((value) => value || directoryResponse.data.classes[0]?.id || ""); setSubjectId((value) => value || directoryResponse.data.subjects[0]?.id || ""); } } catch (e: any) { setError(e?.response?.data?.message ?? "Could not load manual tests."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!manager || !classId || !subjectId) return; setRosterLoading(true); api.get<Student[]>("/manual-tests/roster", { params: { classId, subjectId } }).then(({ data }) => { setRoster(data); setMarks((current) => Object.fromEntries(data.map((student) => [student.id, Array.from({ length: questionCount }, (_, index) => current[student.id]?.[index] ?? 0)]))); }).catch((e) => { setRoster([]); setError(e?.response?.data?.message ?? "Could not load class roster."); }).finally(() => setRosterLoading(false)); }, [manager, classId, subjectId]);
  useEffect(() => { setMarks((current) => Object.fromEntries(roster.map((student) => [student.id, Array.from({ length: questionCount }, (_, index) => Math.min(current[student.id]?.[index] ?? 0, marksPerQuestion))]))); }, [questionCount, marksPerQuestion, roster]);
  const totalMarks = questionCount * marksPerQuestion;
  const setQuestionMark = (studentId: string, index: number, value: number) => setMarks((current) => ({ ...current, [studentId]: (current[studentId] ?? Array(questionCount).fill(0)).map((mark, q) => q === index ? Math.max(0, Math.min(marksPerQuestion, value)) : mark) }));
  const reset = () => { setEditingId(""); setTitle(""); setTestType("WEEKLY"); setHeldAt(today()); setQuestionCount(5); setMarksPerQuestion(5); setRemarks({}); setMarks(Object.fromEntries(roster.map((student) => [student.id, Array(5).fill(0)]))); };
  const save = async () => { if (!title || !classId || !subjectId || !roster.length) return; setSaving(true); setError(""); const payload = { classId, subjectId, title, testType, heldAt, questionCount, marksPerQuestion, results: roster.map((student) => ({ studentUserId: student.id, questionMarks: marks[student.id] ?? Array(questionCount).fill(0), remarks: remarks[student.id] || undefined })) }; try { if (editingId) await api.patch(`/manual-tests/${editingId}`, payload); else await api.post("/manual-tests", payload); reset(); await load(); } catch (e: any) { setError(e?.response?.data?.message ?? "Could not save manual test."); } finally { setSaving(false); } };
  const edit = (test: Test) => { setEditingId(test.id); setClassId(test.class.id); setSubjectId(test.subject.id); setTitle(test.title); setTestType(test.testType); setHeldAt(test.heldAt.slice(0, 10)); setQuestionCount(test.questionCount); setMarksPerQuestion(Number(test.marksPerQuestion)); setRoster(test.results.map((result) => result.student)); setMarks(Object.fromEntries(test.results.map((result) => [result.student.id, result.questionMarks.map(Number)]))); setRemarks(Object.fromEntries(test.results.map((result) => [result.student.id, result.remarks ?? ""]))); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (test: Test) => { if (!window.confirm(`Delete “${test.title}” and all student marks?`)) return; try { await api.delete(`/manual-tests/${test.id}`); await load(); } catch (e: any) { setError(e?.response?.data?.message ?? "Could not delete manual test."); } };
  const studentResult = useMemo(() => tests.flatMap((test) => test.results.map((result) => ({ test, result }))), [tests]);
  if (loading) return <main className="min-h-screen bg-[#f8faff] p-6"><div className="mx-auto max-w-7xl space-y-4">{[1, 2, 3].map((i) => <Skeleton key={i} height={180} variant="rounded" sx={{ borderRadius: 5 }}/>)}</div></main>;
  if (!manager) return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eaf3ff,#fff_48%,#fff8ed)] px-4 py-7 sm:px-8"><section className="mx-auto max-w-6xl"><header><span className="text-xs font-black uppercase tracking-[.22em] text-blue-600">Class performance</span><h1 className="mt-2 text-3xl font-black">Weekly & monthly test results</h1><p className="mt-2 text-sm text-slate-500">See your score and the marks awarded for every question.</p></header>{error && <Alert severity="error" className="mt-4">{error}</Alert>}<div className="mt-6 grid gap-4">{studentResult.map(({ test, result }) => <article key={result.id} className="rounded-[28px] border border-white bg-white/85 p-5 shadow-xl"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">{test.testType} · {test.subject.name}</p><h2 className="mt-1 text-xl font-black">{test.title}</h2><p className="text-sm text-slate-500">{new Date(test.heldAt).toLocaleDateString()} · {test.createdBy.firstName} {test.createdBy.lastName}</p></div><div className="rounded-2xl bg-emerald-50 px-5 py-3 text-center"><p className="text-2xl font-black text-emerald-700">{result.score} / {test.totalMarks}</p><p className="text-xs font-bold text-emerald-600">{result.correctAnswers} fully correct of {test.questionCount}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{result.questionMarks.map((mark, index) => <span key={index} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-black text-slate-700">Q{index + 1}: {mark} / {test.marksPerQuestion}</span>)}</div>{result.remarks && <p className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm text-blue-800">{result.remarks}</p>}</article>)}{!studentResult.length && <div className="rounded-[26px] border border-dashed border-slate-300 py-16 text-center text-slate-500">No weekly or monthly test results yet.</div>}</div></section></main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#edf5ff,#fff_48%,#fff8ed)] px-4 py-7 sm:px-8"><section className="mx-auto max-w-7xl"><header><span className="text-xs font-black uppercase tracking-[.22em] text-violet-600">Teacher assessment book</span><h1 className="mt-2 text-3xl font-black">Manual weekly & monthly tests</h1><p className="mt-2 text-sm text-slate-500">Record every student’s marks question by question; totals and fully-correct answers are calculated automatically.</p></header>{error && <Alert severity="error" className="mt-4" onClose={() => setError("")}>{error}</Alert>}
    <section className="mt-6 rounded-[30px] border border-white bg-white/85 p-5 shadow-xl"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><TextField select label="Class" value={classId} onChange={(e) => setClassId(e.target.value)}>{directory.classes.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}{item.section ? ` - ${item.section}` : ""}</MenuItem>)}</TextField><TextField select label="Subject" value={subjectId} onChange={(e) => setSubjectId(e.target.value)}>{directory.subjects.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><TextField select label="Test type" value={testType} onChange={(e) => setTestType(e.target.value as any)}><MenuItem value="WEEKLY">Weekly</MenuItem><MenuItem value="MONTHLY">Monthly</MenuItem></TextField><TextField type="date" label="Test date" value={heldAt} onChange={(e) => setHeldAt(e.target.value)} InputLabelProps={{ shrink: true }}/><TextField type="number" label="Questions" value={questionCount} onChange={(e) => setQuestionCount(Math.max(1, Math.min(50, Number(e.target.value))))}/><TextField type="number" label="Marks per question" value={marksPerQuestion} onChange={(e) => setMarksPerQuestion(Math.max(0.5, Number(e.target.value)))}/></div><TextField fullWidth sx={{ mt: 2 }} label="Test title" value={title} onChange={(e) => setTitle(e.target.value)} />
      <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-100"><table className="min-w-full text-sm"><thead className="bg-slate-950 text-white"><tr><th className="sticky left-0 bg-slate-950 p-3 text-left">Student</th>{Array.from({ length: questionCount }, (_, index) => <th key={index} className="min-w-24 p-3">Q{index + 1}<span className="block text-[10px] text-white/60">/{marksPerQuestion}</span></th>)}<th className="p-3">Total</th><th className="min-w-52 p-3">Remarks</th></tr></thead><tbody>{roster.map((student) => <tr key={student.id} className="border-t border-slate-100"><td className="sticky left-0 bg-white p-3 font-black">{student.firstName} {student.lastName}<span className="block text-xs font-medium text-slate-400">{student.admissionNo}</span></td>{Array.from({ length: questionCount }, (_, index) => <td key={index} className="p-2"><input aria-label={`${student.firstName} ${student.lastName} question ${index + 1}`} type="number" min="0" max={marksPerQuestion} step="0.5" value={marks[student.id]?.[index] ?? 0} onChange={(e) => setQuestionMark(student.id, index, Number(e.target.value))} className="w-20 rounded-xl border border-slate-200 px-3 py-2 text-center font-black outline-none focus:border-violet-500"/></td>)}<td className="p-3 text-center font-black text-emerald-700">{(marks[student.id] ?? []).reduce((sum, mark) => sum + Number(mark), 0)} / {totalMarks}</td><td className="p-2"><input value={remarks[student.id] ?? ""} onChange={(e) => setRemarks((current) => ({ ...current, [student.id]: e.target.value }))} placeholder="Optional feedback" className="w-full rounded-xl border border-slate-200 px-3 py-2 outline-none focus:border-violet-500"/></td></tr>)}</tbody></table>{rosterLoading && <div className="grid place-items-center py-10"><CircularProgress/></div>}{!rosterLoading && !roster.length && <p className="p-8 text-center text-slate-500">No students found for this class.</p>}</div>
      <div className="mt-4 flex flex-wrap gap-2"><Button variant="contained" startIcon={<AddChartRoundedIcon/>} disabled={saving || !title || !roster.length} onClick={() => void save()} sx={{ borderRadius: 3, fontWeight: 900, background: "linear-gradient(90deg,#2563eb,#7c3aed)" }}>{saving ? <CircularProgress size={19} color="inherit"/> : editingId ? "Update test marks" : "Publish test marks"}</Button>{editingId && <Button onClick={reset}>Cancel editing</Button>}</div>
    </section>
    <section className="mt-6 grid gap-4">{tests.map((test) => <article key={test.id} className="rounded-[26px] border border-white bg-white/85 p-5 shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">{test.testType} · {test.subject.name} · {test.class.name}{test.class.section ? ` ${test.class.section}` : ""}</p><h2 className="mt-1 text-xl font-black">{test.title}</h2><p className="text-sm text-slate-500">{new Date(test.heldAt).toLocaleDateString()} · {test.questionCount} questions · {test.totalMarks} marks</p></div><div className="flex gap-1"><Button size="small" startIcon={<EditRoundedIcon/>} onClick={() => edit(test)}>Edit marks</Button><Button size="small" color="error" startIcon={<DeleteRoundedIcon/>} onClick={() => void remove(test)}>Delete</Button></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{test.results.map((result) => <div key={result.id} className="rounded-2xl bg-slate-50 p-3"><p className="font-black">{result.student.firstName} {result.student.lastName}</p><p className="text-sm font-bold text-emerald-700">{result.score} / {test.totalMarks} · {result.correctAnswers}/{test.questionCount} correct</p></div>)}</div></article>)}{!tests.length && <div className="rounded-[26px] border border-dashed border-slate-300 py-16 text-center text-slate-500">No manual tests recorded yet.</div>}</section>
  </section></main>;
}
