import AssignmentTurnedInRoundedIcon from '@mui/icons-material/AssignmentTurnedInRounded';
import FactCheckRoundedIcon from '@mui/icons-material/FactCheckRounded';
import GroupsRoundedIcon from '@mui/icons-material/GroupsRounded';
import QuizRoundedIcon from '@mui/icons-material/QuizRounded';
import { Skeleton } from '@mui/material';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../lib/api';

type TeacherDashboardData = { assignmentCount:number; studentCount:number; examCount:number; pendingReviews:number; attendanceSessions:number; assignments:Array<{id:string;class:{id:string;name:string;section?:string|null;_count:{students:number}};subject:{id:string;name:string;code?:string|null}}> };

export default function TeacherDashboard(){
  const [data,setData]=useState<TeacherDashboardData|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{api.get<TeacherDashboardData>('/dashboard/teacher').then(r=>setData(r.data)).finally(()=>setLoading(false));},[]);
  const cards=data?[{label:'Assigned classes',value:data.assignmentCount,icon:AssignmentTurnedInRoundedIcon,accent:'from-blue-500 to-cyan-400'},{label:'Students reached',value:data.studentCount,icon:GroupsRoundedIcon,accent:'from-violet-500 to-fuchsia-400'},{label:'Exams created',value:data.examCount,icon:QuizRoundedIcon,accent:'from-emerald-500 to-lime-400'},{label:'Pending reviews',value:data.pendingReviews,icon:FactCheckRoundedIcon,accent:'from-amber-400 to-rose-500'}]:[];
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eaf3ff,#f8fbff_45%,#fff8ed)] px-4 py-7 sm:px-8"><section className="mx-auto max-w-7xl"><header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-xs font-black uppercase tracking-[.22em] text-blue-600">Teacher workspace</span><h1 className="mt-2 text-3xl font-black text-slate-950">Your classes, exams and reviews</h1><p className="mt-2 text-sm text-slate-500">Everything visible here is limited to your assigned classes and subjects.</p></div><div className="flex flex-wrap gap-2"><Link to="/teacher/attendance" className="rounded-2xl bg-white px-4 py-3 text-sm font-black text-slate-700 shadow-sm">Mark attendance</Link><Link to="/teacher/exams/new" className="rounded-2xl bg-gradient-to-r from-blue-600 via-violet-600 to-rose-500 px-4 py-3 text-sm font-black text-white shadow-lg">Create exam</Link></div></header>{loading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><Skeleton key={i} variant="rounded" height={135} sx={{borderRadius:6}}/>)}</div>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=>{const Icon=c.icon;return <article key={c.label} className="card-3d glass-panel rounded-[28px] p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{c.label}</p><p className="mt-2 text-3xl font-black text-slate-950">{c.value}</p></div><div className={`rounded-2xl bg-gradient-to-br ${c.accent} p-3 text-white shadow-lg`}><Icon fontSize="small"/></div></div></article>})}</div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data?.assignments.map(a=><article key={a.id} className="glass-panel rounded-[26px] p-5"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{a.subject.name}</span><h2 className="mt-3 text-lg font-black text-slate-900">{a.class.name}{a.class.section?` · ${a.class.section}`:''}</h2><p className="mt-1 text-sm text-slate-500">{a.class._count.students} students</p></article>)}</div></>}</section></main>;
}
