import GradingRoundedIcon from '@mui/icons-material/GradingRounded';
import { Alert, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Skeleton, TextField } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';

type Attempt={id:string;student:{firstName:string;lastName:string};exam:{title:string;totalMarks:number|string;subject:{name:string}};answers:Array<{id:string;answer:any;autoScore?:number|string|null;manualScore?:number|string|null;feedback?:string|null;question:{id:string;prompt:string;type:string;marks:number|string}}>};

export default function TeacherGrading(){
 const [items,setItems]=useState<Attempt[]>([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Attempt|null>(null); const [scores,setScores]=useState<Record<string,string>>({}); const [feedback,setFeedback]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const {data}=await api.get<Attempt[]>('/exam-attempts/review');setItems(data);}catch{setError('Could not load grading queue.');}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 const manualAnswers=useMemo(()=>selected?.answers.filter(a=>!['MCQ','MULTI_SELECT','TRUE_FALSE','FILL_BLANK','NUMERIC'].includes(a.question.type))??[],[selected]);
 const open=(a:Attempt)=>{setSelected(a);setFeedback('');setScores(Object.fromEntries(a.answers.map(x=>[x.id,String(x.manualScore??x.autoScore??'')])))};
 const save=async()=>{if(!selected)return;setBusy(true);setError('');try{await api.patch(`/exam-attempts/${selected.id}/grade`,{answers:manualAnswers.map(a=>({answerId:a.id,score:Number(scores[a.id]||0),feedback:a.feedback||undefined})),teacherFeedback:feedback||undefined});setSelected(null);await load();}catch(e:any){setError(e?.response?.data?.message??'Could not save grades.');}finally{setBusy(false)}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#edf4ff,#fbfdff_48%,#fff8ed)] px-4 py-6 sm:px-8"><div className="mx-auto max-w-6xl"><header className="mb-6"><span className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Teacher Workspace</span><h1 className="mt-2 text-3xl font-black text-slate-950">Grading queue</h1><p className="mt-2 text-sm text-slate-500">Review written responses and finalize results.</p></header>{error&&<Alert severity="error" className="mb-4">{error}</Alert>}{loading?<div className="space-y-3">{[1,2,3].map(i=><Skeleton key={i} variant="rounded" height={110} sx={{borderRadius:5}} />)}</div>:<div className="space-y-3">{items.map(a=><article key={a.id} className="glass-panel rounded-[26px] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><GradingRoundedIcon className="text-violet-600"/><h2 className="font-black text-slate-900">{a.exam.title}</h2></div><p className="mt-1 text-sm text-slate-500">{a.student.firstName} {a.student.lastName} · {a.exam.subject.name}</p></div><Button variant="contained" onClick={()=>open(a)} sx={{borderRadius:3,fontWeight:900}}>Review answers</Button></div></article>)}{!items.length&&<div className="rounded-[26px] border border-dashed border-slate-300 bg-white/60 py-20 text-center text-slate-500">No attempts are waiting for manual review.</div>}</div>}</div>
 <Dialog open={Boolean(selected)} onClose={()=>!busy&&setSelected(null)} fullWidth maxWidth="md" PaperProps={{sx:{borderRadius:5}}}><DialogTitle sx={{fontWeight:900}}>{selected?.exam.title} · {selected?.student.firstName} {selected?.student.lastName}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{manualAnswers.map(a=><section key={a.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-800">{a.question.prompt}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{typeof a.answer==='string'?a.answer:JSON.stringify(a.answer)}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-slate-500">/{Number(a.question.marks)}</span></div><TextField className="mt-4" label="Score" type="number" value={scores[a.id]??''} onChange={e=>setScores({...scores,[a.id]:e.target.value})} inputProps={{min:0,max:Number(a.question.marks),step:.5}} /></section>)}<TextField fullWidth multiline minRows={3} label="Overall feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} /></div></DialogContent><DialogActions sx={{p:3}}><Button onClick={()=>setSelected(null)} disabled={busy}>Cancel</Button><Button variant="contained" onClick={()=>void save()} disabled={busy} sx={{borderRadius:3,fontWeight:900}}>{busy?<CircularProgress size={20} color="inherit"/>:'Finalize result'}</Button></DialogActions></Dialog>
 </main>;
}
