import { Alert, Button, CircularProgress, Skeleton, TextField } from '@mui/material';
import { useEffect, useState } from 'react';
import { api } from '../../lib/api';

type Submission={id:string;status:string;textAnswer?:string|null;attachmentUrl?:string|null;score?:number|string|null;feedback?:string|null;student:{firstName:string;lastName:string};assignment:{title:string;maxMarks?:number|string|null;class:{name:string;section?:string|null};subject:{name:string}}};
export default function TeacherSubmissionReview(){
 const [items,setItems]=useState<Submission[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [scores,setScores]=useState<Record<string,string>>({});const [feedback,setFeedback]=useState<Record<string,string>>({});const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const {data}=await api.get<Submission[]>('/coursework/submissions');setItems(data);setScores(Object.fromEntries(data.map(s=>[s.id,s.score!=null?String(s.score):''])));setFeedback(Object.fromEntries(data.map(s=>[s.id,s.feedback??''])));}catch{setError('Could not load submissions.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const grade=async(s:Submission)=>{setBusy(s.id);setError('');try{await api.patch(`/coursework/submissions/${s.id}/grade`,{score:Number(scores[s.id]),feedback:feedback[s.id]||undefined});await load();}catch(e:any){setError(e?.response?.data?.message??'Could not grade submission.');}finally{setBusy(null);}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#edf5ff,#fff_48%,#fff8ed)] px-4 py-6 sm:px-8"><section className="mx-auto max-w-6xl"><header className="mb-6"><span className="text-xs font-black uppercase tracking-[.22em] text-violet-600">Teacher workspace</span><h1 className="mt-2 text-3xl font-black text-slate-950">Assignment review</h1><p className="mt-2 text-sm text-slate-500">Review submissions, assign marks and send feedback.</p></header>{error&&<Alert severity="error" className="mb-4" onClose={()=>setError('')}>{error}</Alert>}{loading?<div className="space-y-4">{[1,2,3,4].map(i=><Skeleton key={i} variant="rounded" height={200} sx={{borderRadius:5}}/>)}</div>:<div className="space-y-4">{items.map(s=><article key={s.id} className="rounded-[28px] border border-white bg-white/80 p-5 shadow-[0_18px_55px_rgba(60,80,130,.1)]"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">{s.assignment.subject.name} · {s.assignment.class.name}{s.assignment.class.section?` ${s.assignment.class.section}`:''}</p><h2 className="mt-1 text-xl font-black text-slate-950">{s.assignment.title}</h2><p className="mt-1 text-sm text-slate-500">{s.student.firstName} {s.student.lastName} · {s.status}</p></div>{s.assignment.maxMarks&&<div className="text-sm font-black text-slate-500">Max {s.assignment.maxMarks}</div>}</div><div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-700 whitespace-pre-wrap">{s.textAnswer||'No text answer submitted.'}</div>{s.attachmentUrl&&<a href={s.attachmentUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-bold text-blue-600">Open attachment</a>}<div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto] md:items-end"><TextField label="Score" type="number" value={scores[s.id]??''} onChange={e=>setScores(v=>({...v,[s.id]:e.target.value}))}/><TextField label="Feedback" value={feedback[s.id]??''} onChange={e=>setFeedback(v=>({...v,[s.id]:e.target.value}))}/><Button variant="contained" disabled={busy===s.id||scores[s.id]===''} onClick={()=>void grade(s)} sx={{borderRadius:3,fontWeight:900,px:3,py:1.8,background:'linear-gradient(90deg,#2563eb,#7c3aed)'}}>{busy===s.id?<CircularProgress size={18} color="inherit"/>:'Save grade'}</Button></div></article>)}{!items.length&&<div className="rounded-[26px] border border-dashed border-slate-300 py-16 text-center text-slate-500">No submissions yet.</div>}</div>}</section></main>;
}
