import { AccountBalanceWalletRounded, CheckCircleRounded, GroupsRounded, PaymentsRounded, ReceiptLongRounded, WarningAmberRounded } from '@mui/icons-material';
import { Alert, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Skeleton, TextField } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../features/auth/AuthProvider';
import { api } from '../../lib/api';

type StudentCard={studentProfileId:string;name:string;admissionNo:string;className:string;monthlyFee:number;paidAmount:number;status:string};
type ClassRow={classId:string;className:string;monthlyAmount:number;students:number;paid:number;remaining:number;expected:number;collected:number;pending:number;recoveryRate:number};
type Batch={id:string;status:string;totalAmount:number;studentCount:number;firstName:string;lastName:string;createdAt:string;submittedAt?:string|null};
type Dashboard={month:string;expected:number;received:number;principalCollected:number;cashPendingWithStaff:number;remaining:number;paidStudents:number;totalStudents:number;classRows:ClassRow[];studentCards:StudentCard[];batches:Batch[]};
type Due={studentProfileId:string;name:string;admissionNo:string;className:string;monthlyFee:number;unpaidMonths:number;dueAmount:number;missingMonths:string[]};
const money=(n:number)=>`Rs ${Number(n||0).toLocaleString()}`;

export default function FeeRecoveryPage(){
 const {user}=useAuth(); const principal=user?.role==='PRINCIPAL';
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState<Dashboard|null>(null),[dues,setDues]=useState<Due[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const [payStudent,setPayStudent]=useState<StudentCard|null>(null),[amount,setAmount]=useState(''),[method,setMethod]=useState('CASH'),[reference,setReference]=useState('');
 const [batch,setBatch]=useState<any|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([api.get('/fees/recovery-dashboard',{params:{month}}),api.get('/fees/student-dues',{params:{months:12}})]);setData(a.data);setDues(b.data);}catch(e:any){setError(e?.response?.data?.message??'Could not load fee recovery.');}finally{setLoading(false)}};
 useEffect(()=>{load()},[month]);
 const openBatch=useMemo(()=>data?.batches.find(x=>x.status==='OPEN'),[data]);
 const submitted=data?.batches.filter(x=>x.status==='SUBMITTED')??[];
 const receive=async()=>{if(!payStudent)return;setBusy('pay');try{await api.post('/fees/receive',{studentProfileId:payStudent.studentProfileId,month,amount:Number(amount),method,reference:reference||undefined});setPayStudent(null);setAmount('');setReference('');await load();}catch(e:any){setError(e?.response?.data?.message??'Could not record fee.');}finally{setBusy('')}};
 const submitBatch=async(id:string)=>{setBusy(id);try{await api.post(`/fees/batches/${id}/submit`);await load();}catch(e:any){setError(e?.response?.data?.message??'Could not submit batch.');}finally{setBusy('')}};
 const inspect=async(id:string)=>{setBusy(id);try{setBatch((await api.get(`/fees/batches/${id}`)).data);}catch(e:any){setError(e?.response?.data?.message??'Could not load batch.');}finally{setBusy('')}};
 const collect=async(id:string)=>{setBusy(id);try{await api.patch(`/fees/batches/${id}/collect`,{});setBatch(null);await load();}catch(e:any){setError(e?.response?.data?.message??'Could not collect batch.');}finally{setBusy('')}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eaf4ff,transparent_32%),radial-gradient(circle_at_top_right,#fff2df,transparent_30%),#f7f9ff] p-4 text-slate-800 md:p-8"><section className="mx-auto max-w-7xl">
  <header className="rounded-[32px] border border-white bg-white/85 p-6 shadow-[0_30px_90px_rgba(70,90,140,.14)] backdrop-blur-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-600">Finance intelligence</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Fee Recovery Center</h1><p className="mt-2 max-w-2xl text-slate-500">Track student dues, staff cash accountability and money actually handed over to the Principal.</p></div><TextField label="Recovery month" type="month" value={month} onChange={e=>setMonth(e.target.value)} InputLabelProps={{shrink:true}}/></div></header>
  {error&&<Alert severity="error" className="mt-5">{error}</Alert>}
  {loading?<div className="mt-6 grid gap-4 md:grid-cols-3">{[1,2,3,4,5,6].map(x=><Skeleton key={x} height={120} variant="rounded" sx={{borderRadius:5}}/>)}</div>:data&&<>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[PaymentsRounded,'Expected this month',money(data.expected),'from all configured classes'],[CheckCircleRounded,'Received from students',money(data.received),`${data.paidStudents} of ${data.totalStudents} students`],[AccountBalanceWalletRounded,'Principal collected',money(data.principalCollected),'verified school cash'],[WarningAmberRounded,'Cash with staff',money(data.cashPendingWithStaff),'received but not handed over'],[GroupsRounded,'Students remaining',String(data.totalStudents-data.paidStudents),money(data.remaining)+' outstanding'],[ReceiptLongRounded,'Recovery rate',`${data.expected?Math.round(data.received/data.expected*1000)/10:0}%`,'student fee recovery']].map(([Icon,title,value,note]:any)=><article key={title} className="rounded-[26px] border border-white bg-white/90 p-5 shadow-xl transition hover:-translate-y-1"><div className="inline-flex rounded-2xl bg-gradient-to-br from-emerald-500 to-cyan-500 p-3 text-white"><Icon/></div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">{title}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-sm text-slate-500">{note}</p></article>)}</section>
   {!principal&&<section className="mt-6 rounded-[30px] border border-amber-100 bg-gradient-to-r from-amber-50 to-orange-50 p-6 shadow-xl"><h2 className="text-xl font-black">My cash handover</h2>{openBatch?<div className="mt-4 flex flex-wrap items-center justify-between gap-4"><div><p className="text-3xl font-black">{money(openBatch.totalAmount)}</p><p className="text-sm text-slate-600">{openBatch.studentCount} student payments currently in your custody</p></div><div className="flex gap-2"><Button variant="outlined" onClick={()=>inspect(openBatch.id)}>View students</Button><Button variant="contained" disabled={busy===openBatch.id||!Number(openBatch.studentCount)} onClick={()=>submitBatch(openBatch.id)}>{busy===openBatch.id?<CircularProgress size={20}/>:<>Submit to Principal</>}</Button></div></div>:<p className="mt-3 text-slate-500">No open cash batch. Receiving a student fee will create one automatically.</p>}</section>}
   {principal&&submitted.length>0&&<section className="mt-6 rounded-[30px] border border-emerald-100 bg-white/90 p-6 shadow-xl"><h2 className="text-xl font-black">Cash waiting for collection</h2><div className="mt-4 grid gap-3">{submitted.map(b=><div key={b.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-emerald-50 p-4"><div><p className="font-black">{b.firstName} {b.lastName}</p><p className="text-sm text-slate-600">{b.studentCount} students · {money(b.totalAmount)}</p></div><Button variant="contained" onClick={()=>inspect(b.id)}>Review & collect</Button></div>)}</div></section>}
   <section className="mt-6 rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><h2 className="text-xl font-black">Student recovery cards</h2><p className="text-sm text-slate-500">Who paid this month and who is still pending.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.studentCards.map(s=><article key={s.studentProfileId} className={`rounded-2xl border p-4 ${s.status==='PAID'?'border-emerald-100 bg-emerald-50/70':'border-rose-100 bg-rose-50/60'}`}><div className="flex items-start justify-between gap-2"><div><p className="font-black">{s.name}</p><p className="text-xs text-slate-500">{s.admissionNo} · {s.className}</p></div><Chip size="small" label={s.status} color={s.status==='PAID'?'success':'error'}/></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-slate-400">Monthly fee</p><p className="text-lg font-black">{money(s.monthlyFee)}</p></div>{s.status!=='PAID'&&<Button size="small" variant="contained" onClick={()=>{setPayStudent(s);setAmount(String(s.monthlyFee))}}>Receive fee</Button>}</div></article>)}</div></section>
   <section className="mt-6 overflow-hidden rounded-[30px] border border-white bg-white/90 shadow-xl"><div className="p-6"><h2 className="text-xl font-black">Class-wise recovery</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr>{['Class','Paid','Remaining','Expected','Recovered','Outstanding','Rate'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{data.classRows.map(r=><tr key={r.classId} className="border-t border-slate-100"><td className="p-4 font-black">{r.className}</td><td className="p-4">{r.paid}/{r.students}</td><td className="p-4 font-bold text-rose-600">{r.remaining}</td><td className="p-4">{money(r.expected)}</td><td className="p-4 text-emerald-700">{money(r.collected)}</td><td className="p-4">{money(r.pending)}</td><td className="p-4"><Chip label={`${r.recoveryRate}%`} color={r.recoveryRate>=90?'success':r.recoveryRate>=70?'warning':'error'}/></td></tr>)}</tbody></table></div></section>
   <section className="mt-6 overflow-hidden rounded-[30px] border border-white bg-white/90 shadow-xl"><div className="p-6"><h2 className="text-xl font-black">Outstanding fee ranking</h2><p className="text-sm text-slate-500">Last 12 months, highest outstanding students first.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr>{['Rank','Student','Class','Unpaid months','Outstanding','Missing months'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{dues.map((d,i)=><tr key={d.studentProfileId} className="border-t border-slate-100"><td className="p-4 font-black">#{i+1}</td><td className="p-4"><p className="font-black">{d.name}</p><p className="text-xs text-slate-400">{d.admissionNo}</p></td><td className="p-4">{d.className}</td><td className="p-4 font-black text-rose-600">{d.unpaidMonths}</td><td className="p-4 font-black">{money(d.dueAmount)}</td><td className="p-4 text-xs text-slate-500">{d.missingMonths.join(' · ')||'Clear'}</td></tr>)}</tbody></table></div></section>
  </>}
 </section>
 <Dialog open={!!payStudent} onClose={()=>setPayStudent(null)} fullWidth maxWidth="sm"><DialogTitle>Receive monthly fee</DialogTitle><DialogContent className="grid gap-4 pt-3"><p className="font-bold">{payStudent?.name} · {month}</p><TextField label="Amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><TextField select label="Payment method" value={method} onChange={e=>setMethod(e.target.value)}>{['CASH','BANK','EASYPAISA','JAZZCASH','OTHER'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Reference (optional)" value={reference} onChange={e=>setReference(e.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setPayStudent(null)}>Cancel</Button><Button variant="contained" disabled={busy==='pay'||!Number(amount)} onClick={receive}>{busy==='pay'?<CircularProgress size={20}/>:principal?'Receive & approve':'Receive into my cash batch'}</Button></DialogActions></Dialog>
 <Dialog open={!!batch} onClose={()=>setBatch(null)} fullWidth maxWidth="md"><DialogTitle>Recovery batch · {batch?.firstName} {batch?.lastName}</DialogTitle><DialogContent><div className="mb-4 rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-black">{money(batch?.totalAmount)}</p><p className="text-sm text-slate-500">{batch?.studentCount} students · {batch?.status}</p></div><div className="max-h-[45vh] overflow-auto">{batch?.payments?.map((p:any)=><div key={p.id} className="flex justify-between border-b border-slate-100 py-3"><div><p className="font-bold">{p.firstName} {p.lastName}</p><p className="text-xs text-slate-500">{p.admissionNo} · {p.className}{p.section?` - ${p.section}`:''} · {p.month}</p></div><p className="font-black">{money(p.amount)}</p></div>)}</div></DialogContent><DialogActions><Button onClick={()=>setBatch(null)}>Close</Button>{principal&&batch?.status==='SUBMITTED'&&<Button variant="contained" color="success" disabled={busy===batch.id} onClick={()=>collect(batch.id)}>{busy===batch.id?<CircularProgress size={20}/>:<>Confirm cash collected</>}</Button>}</DialogActions></Dialog>
 </main>;
}
