import { AccountBalanceWalletRounded, CheckCircleRounded, GroupsRounded, PaymentsRounded, PendingActionsRounded, ReceiptLongRounded, WarningAmberRounded } from '@mui/icons-material';
import { Alert, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Skeleton, TextField } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { useAuth } from '../../features/auth/AuthProvider';

type Dashboard={month:string;expected:number;received:number;principalCollected:number;cashPendingWithStaff:number;remaining:number;paidStudents:number;totalStudents:number;classRows:any[];studentCards:any[];batches:any[]};
const money=(n:number)=>new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(n||0);

export default function FeesRecoveryPage(){
 const {user}=useAuth();const isPrincipal=user?.role==='PRINCIPAL';
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState<Dashboard|null>(null),[dues,setDues]=useState<any[]>([]),[batches,setBatches]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [student,setStudent]=useState<any|null>(null),[amount,setAmount]=useState(''),[method,setMethod]=useState('CASH'),[reference,setReference]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [d,u,b]=await Promise.all([api.get('/fees/recovery-dashboard',{params:{month}}),api.get('/fees/student-dues',{params:{months:12}}),api.get('/fees/batches')]);setData(d.data);setDues(u.data);setBatches(b.data);}catch(e:any){setError(e?.response?.data?.message??'Could not load fees recovery.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[month]);
 const receive=async()=>{if(!student)return;setBusy('receive');try{await api.post('/fees/receive',{studentProfileId:student.studentProfileId,month,amount:Number(amount||student.monthlyFee),method,reference:reference||undefined});setStudent(null);setAmount('');setReference('');setSuccess(isPrincipal?'Fee received and approved.':'Fee received. It is now pending Principal cash collection.');await load();}catch(e:any){setError(e?.response?.data?.message??'Could not record fee.');}finally{setBusy('');}};
 const submitBatch=async(id:string)=>{setBusy(id);try{await api.post(`/fees/batches/${id}/submit`);setSuccess('Cash batch submitted to Principal.');await load();}catch(e:any){setError(e?.response?.data?.message??'Could not submit batch.');}finally{setBusy('');}};
 const collectBatch=async(id:string)=>{setBusy(id);try{await api.patch(`/fees/batches/${id}/collect`,{});setSuccess('Batch collected from Staff and all student payments approved.');await load();}catch(e:any){setError(e?.response?.data?.message??'Could not collect batch.');}finally{setBusy('');}};
 const sorted=useMemo(()=>[...dues].sort((a,b)=>b.dueAmount-a.dueAmount),[dues]);
 if(loading&&!data)return <main className="min-h-screen bg-[#f7f9ff] p-6"><div className="mx-auto max-w-7xl space-y-4">{[1,2,3,4,5].map(x=><Skeleton key={x} height={120} variant="rounded" sx={{borderRadius:5}}/>)}</div></main>;
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#e8f2ff,transparent_32%),radial-gradient(circle_at_top_right,#fff1df,transparent_28%),#f8faff] p-4 md:p-8 text-slate-800"><section className="mx-auto max-w-7xl">
  <header className="rounded-[32px] border border-white bg-white/80 p-6 shadow-[0_28px_80px_rgba(60,80,130,.12)] backdrop-blur-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-600">Fee Recovery Control</p><h1 className="mt-2 text-3xl font-black md:text-4xl">{isPrincipal?'Principal Collection Center':'Staff Fee Recovery'}</h1><p className="mt-2 max-w-3xl text-slate-500">Track who paid, who still owes, cash currently held by Staff, and what has actually been collected by the Principal.</p></div><TextField type="month" label="Recovery month" value={month} onChange={e=>setMonth(e.target.value)} InputLabelProps={{shrink:true}}/></div></header>
  {error&&<Alert severity="error" className="mt-4" onClose={()=>setError('')}>{error}</Alert>}{success&&<Alert severity="success" className="mt-4" onClose={()=>setSuccess('')}>{success}</Alert>}
  {data&&<section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[
   ['Expected',money(data.expected),AccountBalanceWalletRounded,'from-blue-600 to-cyan-400'],['Students paid',`${data.paidStudents}/${data.totalStudents}`,GroupsRounded,'from-emerald-600 to-lime-400'],['Received',money(data.received),PaymentsRounded,'from-violet-600 to-fuchsia-400'],['With staff',money(data.cashPendingWithStaff),PendingActionsRounded,'from-amber-500 to-orange-400'],['Principal collected',money(data.principalCollected),CheckCircleRounded,'from-emerald-500 to-teal-400'],['Still due',money(data.remaining),WarningAmberRounded,'from-rose-600 to-orange-400']
  ].map(([label,value,Icon,grad]:any)=><article key={label} className="rounded-[25px] border border-white bg-white/85 p-5 shadow-lg transition hover:-translate-y-1"><div className={`inline-flex rounded-2xl bg-gradient-to-br ${grad} p-3 text-white`}><Icon/></div><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>)}</section>}

  <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
   <article className="rounded-[30px] border border-white bg-white/85 p-6 shadow-xl"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Student recovery cards</h2><p className="text-sm text-slate-500">Current month status. Click an unpaid student to receive fee.</p></div><ReceiptLongRounded className="text-indigo-600"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{data?.studentCards.map(s=><button key={s.studentProfileId} disabled={s.status==='PAID'} onClick={()=>{setStudent(s);setAmount(String(s.monthlyFee));}} className={`rounded-[22px] border p-4 text-left transition ${s.status==='PAID'?'border-emerald-200 bg-emerald-50/70':'border-slate-200 bg-white hover:-translate-y-1 hover:border-indigo-300 hover:shadow-lg'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{s.name}</p><p className="text-xs text-slate-500">{s.admissionNo} · {s.className}</p></div><span className={`rounded-full px-3 py-1 text-[11px] font-black ${s.status==='PAID'?'bg-emerald-100 text-emerald-700':'bg-rose-100 text-rose-700'}`}>{s.status}</span></div><p className="mt-4 text-lg font-black">{money(s.monthlyFee)}</p>{s.status==='PAID'&&<p className="text-xs font-bold text-emerald-700">Received {money(s.paidAmount)}</p>}</button>)}</div></article>
   <article className="rounded-[30px] border border-white bg-white/85 p-6 shadow-xl"><h2 className="text-xl font-black">Highest outstanding</h2><p className="text-sm text-slate-500">Last 12 months, ranked by unpaid amount.</p><div className="mt-5 space-y-3">{sorted.slice(0,10).map((s,i)=><div key={s.studentProfileId} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-black">#{i+1} {s.name}</p><p className="text-xs text-slate-500">{s.className} · {s.unpaidMonths} unpaid months</p></div><p className="font-black text-rose-600">{money(s.dueAmount)}</p></div><p className="mt-2 text-[11px] font-bold text-slate-400">{s.missingMonths.join(' · ')||'No outstanding month'}</p></div>)}</div></article>
  </section>

  <section className="mt-6 rounded-[30px] border border-white bg-white/85 p-6 shadow-xl"><h2 className="text-xl font-black">Class-wise recovery</h2><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-3">Class</th><th className="p-3">Paid / Total</th><th className="p-3">Expected</th><th className="p-3">Recovered</th><th className="p-3">Pending</th><th className="p-3">Recovery</th></tr></thead><tbody>{data?.classRows.map(r=><tr key={r.classId} className="border-t border-slate-100"><td className="p-3 font-black">{r.className}</td><td className="p-3">{r.paid}/{r.students} <span className="text-rose-500">({r.remaining} remaining)</span></td><td className="p-3">{money(r.expected)}</td><td className="p-3 font-bold text-emerald-700">{money(r.collected)}</td><td className="p-3 font-bold text-rose-600">{money(r.pending)}</td><td className="p-3"><span className="rounded-full bg-indigo-50 px-3 py-1 font-black text-indigo-700">{r.recoveryRate}%</span></td></tr>)}</tbody></table></div></section>

  <section className="mt-6 rounded-[30px] border border-white bg-white/85 p-6 shadow-xl"><h2 className="text-xl font-black">{isPrincipal?'Staff cash collection queue':'My cash batches'}</h2><p className="text-sm text-slate-500">A batch can contain 3, 15, or any number of student payments. Principal collection approves every payment inside that batch.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{batches.map(b=><article key={b.id} className="rounded-[22px] border border-slate-100 bg-slate-50 p-5"><div className="flex justify-between gap-3"><div><p className="font-black">{b.firstName} {b.lastName}</p><p className="text-xs text-slate-500">{b.studentCount} student payments</p></div><span className="h-fit rounded-full bg-white px-3 py-1 text-xs font-black">{b.status}</span></div><p className="mt-4 text-2xl font-black">{money(Number(b.totalAmount))}</p><p className="text-xs text-slate-400">Cash accountable to this batch</p>{!isPrincipal&&b.status==='OPEN'&&<Button fullWidth sx={{mt:2,borderRadius:3,fontWeight:900}} variant="contained" disabled={busy===b.id||Number(b.studentCount)===0} onClick={()=>void submitBatch(b.id)}>{busy===b.id?<CircularProgress size={20} color="inherit"/>:'Submit cash to Principal'}</Button>}{isPrincipal&&b.status==='SUBMITTED'&&<Button fullWidth color="success" sx={{mt:2,borderRadius:3,fontWeight:900}} variant="contained" disabled={busy===b.id} onClick={()=>void collectBatch(b.id)}>{busy===b.id?<CircularProgress size={20} color="inherit"/>:'Collect & approve batch'}</Button>}</article>)}</div></section>
 </section>
 <Dialog open={Boolean(student)} onClose={()=>setStudent(null)} fullWidth maxWidth="sm"><DialogTitle>Receive monthly fee</DialogTitle><DialogContent className="space-y-4 pt-3"><Alert severity="info">{student?.name} · {student?.className} · {month}</Alert><TextField fullWidth label="Amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><TextField select fullWidth label="Method" value={method} onChange={e=>setMethod(e.target.value)}><MenuItem value="CASH">Cash</MenuItem><MenuItem value="BANK">Bank</MenuItem><MenuItem value="EASYPAISA">Easypaisa</MenuItem><MenuItem value="JAZZCASH">JazzCash</MenuItem><MenuItem value="OTHER">Other</MenuItem></TextField><TextField fullWidth label="Reference (optional)" value={reference} onChange={e=>setReference(e.target.value)}/>{!isPrincipal&&<Alert severity="warning">This payment will be marked received from the student but remains pending until the Principal collects your recovery batch.</Alert>}</DialogContent><DialogActions><Button onClick={()=>setStudent(null)}>Cancel</Button><Button variant="contained" onClick={()=>void receive()} disabled={busy==='receive'||!Number(amount)}>{busy==='receive'?<CircularProgress size={20} color="inherit"/>:'Receive fee'}</Button></DialogActions></Dialog>
 </main>;
}