import AssignmentTurnedInRoundedIcon from "@mui/icons-material/AssignmentTurnedInRounded";
import PersonRoundedIcon from "@mui/icons-material/PersonRounded";
import ScheduleRoundedIcon from "@mui/icons-material/ScheduleRounded";
import { Alert, Button, CircularProgress, MenuItem, Skeleton, TextField } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import FileUpload, { openStorageReference } from "../../components/storage/FileUpload";
import { api } from "../../lib/api";

type Assignment = {
  id: string; title: string; instructions: string; attachmentUrl?: string | null; dueAt?: string | null;
  maxMarks?: number | string | null; subject: { id: string; name: string }; class?: { name: string; section?: string | null };
  teacher?: { firstName: string; lastName: string } | null;
  submissions: Array<{ id: string; status: string; textAnswer?: string | null; attachmentUrl?: string | null; score?: number | string | null; feedback?: string | null }>;
};

export default function StudentAssignments() {
  const [items, setItems] = useState<Assignment[]>([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState<string | null>(null);
  const [subjectId, setSubjectId] = useState(""), [answers, setAnswers] = useState<Record<string, string>>({}), [links, setLinks] = useState<Record<string, string>>({});
  const [editing, setEditing] = useState<Record<string, boolean>>({}), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = async () => { setLoading(true); try { const { data } = await api.get<Assignment[]>("/coursework/assignments"); setItems(data); setSubjectId((value) => value || data[0]?.subject.id || ""); setAnswers(Object.fromEntries(data.map((a) => [a.id, a.submissions[0]?.textAnswer ?? ""]))); setLinks(Object.fromEntries(data.map((a) => [a.id, a.submissions[0]?.attachmentUrl ?? ""]))); } catch { setError("Could not load assignments."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const subjects = useMemo(() => Array.from(new Map(items.map((item) => [item.subject.id, item.subject])).values()), [items]);
  const filtered = useMemo(() => items.filter((item) => item.subject.id === subjectId), [items, subjectId]);
  const subjectTeacher = filtered.find((item) => item.teacher)?.teacher;
  const nextDeadline = filtered.filter((item) => item.dueAt && new Date(item.dueAt) >= new Date()).sort((a, b) => +new Date(a.dueAt!) - +new Date(b.dueAt!))[0]?.dueAt;
  const save = async (id: string, submit: boolean) => { setSaving(id); setError(""); setMessage(""); try { await api.put(`/coursework/assignments/${id}/submission`, { textAnswer: answers[id] || undefined, attachmentUrl: links[id] || undefined, submit }); setMessage(submit ? "Assignment submitted." : "Draft saved."); setEditing((value) => ({ ...value, [id]: false })); await load(); } catch (e: any) { setError(e?.response?.data?.message ?? "Submission could not be saved."); } finally { setSaving(null); } };
  if (loading) return <main className="min-h-screen bg-[#f8faff] p-6"><div className="mx-auto max-w-5xl space-y-4">{[1, 2, 3].map((i) => <Skeleton key={i} variant="rounded" height={220} sx={{ borderRadius: 5 }} />)}</div></main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eaf3ff,#fff_45%,#fff8ed)] px-4 py-6 sm:px-8"><section className="mx-auto max-w-5xl">
    <header className="mb-6"><span className="text-xs font-black uppercase tracking-[.22em] text-indigo-600">Student coursework</span><h1 className="mt-2 text-3xl font-black text-slate-950">Submit an assignment</h1><p className="mt-2 text-sm text-slate-500">Choose the subject first, confirm the teacher and deadline, then submit the correct work.</p></header>
    {error && <Alert severity="error" className="mb-4" onClose={() => setError("")}>{error}</Alert>}{message && <Alert severity="success" className="mb-4" onClose={() => setMessage("")}>{message}</Alert>}
    {subjects.length ? <section className="mb-5 rounded-[28px] border border-white bg-white/85 p-5 shadow-[0_18px_55px_rgba(60,80,130,.12)] backdrop-blur-xl">
      <TextField select fullWidth label="Which subject are you submitting?" value={subjectId} onChange={(event) => setSubjectId(event.target.value)}>{subjects.map((subject) => <MenuItem key={subject.id} value={subject.id}>{subject.name}</MenuItem>)}</TextField>
      <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-indigo-50 p-4"><AssignmentTurnedInRoundedIcon className="text-indigo-600"/><p className="mt-2 text-xs font-bold text-slate-500">Subject</p><p className="font-black text-slate-900">{filtered[0]?.subject.name}</p></div><div className="rounded-2xl bg-emerald-50 p-4"><PersonRoundedIcon className="text-emerald-600"/><p className="mt-2 text-xs font-bold text-slate-500">Class teacher</p><p className="font-black text-slate-900">{subjectTeacher ? `${subjectTeacher.firstName} ${subjectTeacher.lastName}` : "Teacher not assigned"}</p></div><div className="rounded-2xl bg-rose-50 p-4"><ScheduleRoundedIcon className="text-rose-600"/><p className="mt-2 text-xs font-bold text-slate-500">Next deadline</p><p className="font-black text-slate-900">{nextDeadline ? new Date(nextDeadline).toLocaleString() : "No upcoming deadline"}</p></div></div>
    </section> : null}
    <div className="space-y-4">{filtered.map((assignment) => { const submission = assignment.submissions[0]; const graded = submission?.status === "GRADED"; const submitted = Boolean(submission && ["SUBMITTED", "LATE"].includes(submission.status)); const canEdit = !graded && (!submitted || editing[assignment.id]); return <article key={assignment.id} className="rounded-[28px] border border-white bg-white/80 p-5 shadow-[0_18px_55px_rgba(60,80,130,.1)] backdrop-blur-xl">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">{assignment.subject.name}{assignment.class ? ` · ${assignment.class.name}${assignment.class.section ? ` ${assignment.class.section}` : ""}` : ""}</p><h2 className="mt-1 text-xl font-black text-slate-950">{assignment.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{assignment.instructions}</p>{assignment.attachmentUrl && <Button size="small" sx={{ mt: 1 }} onClick={() => void openStorageReference(assignment.attachmentUrl!)}>Open teacher attachment</Button>}</div><div className="rounded-2xl bg-slate-50 px-4 py-3 text-right text-xs font-bold text-slate-500"><p>{assignment.dueAt ? `Due ${new Date(assignment.dueAt).toLocaleString()}` : "No deadline"}</p>{assignment.maxMarks && <p className="mt-1">{assignment.maxMarks} marks</p>}</div></div>
      <div className="mt-5 grid gap-3"><TextField multiline minRows={4} label="Your answer" value={answers[assignment.id] ?? ""} onChange={(event) => setAnswers((value) => ({ ...value, [assignment.id]: event.target.value }))} disabled={!canEdit}/><FileUpload category="submission" label="Upload answer file" value={links[assignment.id] ?? ""} onChange={(value) => setLinks((current) => ({ ...current, [assignment.id]: value }))} disabled={!canEdit}/></div>
      {submission && <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm"><div className="font-black text-slate-700">Status: {submission.status}</div>{submission.score != null && <div className="mt-1 font-bold text-emerald-700">Score: {submission.score}{assignment.maxMarks ? ` / ${assignment.maxMarks}` : ""}</div>}{submission.feedback && <div className="mt-1 text-slate-600">Feedback: {submission.feedback}</div>}</div>}
      <div className="mt-5 flex flex-wrap gap-2">{canEdit && <><Button variant="outlined" onClick={() => void save(assignment.id, false)} disabled={saving === assignment.id} sx={{ borderRadius: 3, fontWeight: 800 }}>Save draft</Button><Button variant="contained" onClick={() => void save(assignment.id, true)} disabled={saving === assignment.id || (!answers[assignment.id] && !links[assignment.id])} sx={{ borderRadius: 3, fontWeight: 900, background: "linear-gradient(90deg,#2563eb,#7c3aed)" }}>{saving === assignment.id ? <CircularProgress size={18} color="inherit"/> : submitted ? "Resubmit assignment" : "Submit assignment"}</Button></>}{submitted && !editing[assignment.id] && <Button variant="outlined" onClick={() => setEditing((value) => ({ ...value, [assignment.id]: true }))}>Edit and resubmit</Button>}{graded && <span className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-black text-emerald-700">Graded submissions are locked</span>}</div>
    </article>; })}{!filtered.length && <div className="rounded-[26px] border border-dashed border-slate-300 py-16 text-center text-slate-500">No assignments for this subject yet.</div>}</div>
  </section></main>;
}
