import { AssignmentRounded, CheckCircleRounded, DescriptionRounded, MenuBookRounded, ScheduleRounded } from '@mui/icons-material';
import { Alert, Chip, Skeleton } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../../lib/api';

type Submission = { id:string; status:string; submittedAt?:string|null; score?:number|string|null; feedback?:string|null; gradedAt?:string|null };
type Assignment = { id:string; title:string; instructions:string; dueAt?:string|null; maxMarks?:number|string|null; attachmentUrl?:string|null; subject:{name:string;code?:string|null}; submission?:Submission|null };
type Material = { id:string; title:string; description?:string|null; fileUrl?:string|null; externalUrl?:string|null; createdAt:string; subject:{name:string} };
type Syllabus = { id:string; title:string; description?:string|null; isCompleted:boolean; completedAt?:string|null; subject:{name:string} };
type Payload = { student:{id:string;user:{firstName:string;lastName:string};class?:{name:string;section?:string|null}|null};relation?:string|null;assignments:Assignment[];materials:Material[];syllabus:Syllabus[] };

function assignmentColor(status?:string){if(status==='GRADED')return 'success';if(status==='SUBMITTED'||status==='LATE')return 'info';if(status==='DRAFT')return 'warning';return 'default';}

export default function ParentCourseworkPage(){
 const [params]=useSearchParams();const studentId=params.get('studentId')||'';
 const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{if(!studentId){setError('Select a child from the Parent dashboard first.');setLoading(false);return;}setLoading(true);setError('');api.get<Payload>(`/parent-coursework/${studentId}`).then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.message??'Could not load child coursework.')).finally(()=>setLoading(false));},[studentId]);
 const syllabusStats=useMemo(()=>{const total=data?.syllabus.length??0,done=data?.syllabus.filter(x=>x.isCompleted).length??0;return{total,done,percent:total?Math.round(done/total*100):0};},[data]);
 if(loading)return <main className="min-h-screen bg-[#f8fbff] p-6"><div className="mx-auto max-w-6xl space-y-4">{[1,2,3,4].map(i=><Skeleton key={i} height={130} variant="rounded" sx={{borderRadius:5}}/>)}</div></main>;
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eef5ff,transparent_34%),radial-gradient(circle_at_top_right,#fff4e8,transparent_28%),#f8faff] p-4 md:p-8"><section className="mx-auto max-w-6xl">
  {error&&<Alert severity="error">{error}</Alert>}
  {data&&<><header className="rounded-[32px] border border-white bg-white/90 p-6 shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Parent · read only</p><h1 className="mt-2 text-3xl font-black">Coursework overview</h1><p className="mt-2 text-slate-500">{data.student.user.firstName} {data.student.user.lastName} · {data.student.class?`${data.student.class.name}${data.student.class.section?` - ${data.student.class.section}`:''}`:'No class assigned'}{data.relation?` · ${data.relation}`:''}</p></header>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<AssignmentRounded/>} label="Assignments" value={data.assignments.length}/><Metric icon={<CheckCircleRounded/>} label="Graded" value={data.assignments.filter(x=>x.submission?.status==='GRADED').length}/><Metric icon={<DescriptionRounded/>} label="Materials" value={data.materials.length}/><Metric icon={<MenuBookRounded/>} label="Syllabus progress" value={`${syllabusStats.percent}%`}/></section>
   <section className="mt-6 rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><h2 className="text-xl font-black">Assignments & submissions</h2><p className="text-sm text-slate-500">You can review status and teacher feedback, but cannot submit on behalf of the student.</p><div className="mt-5 grid gap-3">{data.assignments.length?data.assignments.map(a=><article key={a.id} className="rounded-[22px] border border-slate-100 bg-slate-50/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-violet-600">{a.subject.name}</p><h3 className="mt-1 font-black text-slate-900">{a.title}</h3><p className="mt-2 text-sm text-slate-500">{a.instructions}</p></div><Chip size="small" label={a.submission?.status??'NOT SUBMITTED'} color={assignmentColor(a.submission?.status) as any}/></div><div className="mt-4 grid gap-3 sm:grid-cols-3 text-xs"><div><p className="text-slate-400">Due</p><p className="font-bold">{a.dueAt?new Date(a.dueAt).toLocaleString():'No deadline'}</p></div><div><p className="text-slate-400">Score</p><p className="font-bold">{a.submission?.score!=null?`${Number(a.submission.score)}${a.maxMarks!=null?` / ${Number(a.maxMarks)}`:''}`:'—'}</p></div><div><p className="text-slate-400">Submitted</p><p className="font-bold">{a.submission?.submittedAt?new Date(a.submission.submittedAt).toLocaleString():'—'}</p></div></div>{a.submission?.feedback&&<div className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-800"><b>Teacher feedback:</b> {a.submission.feedback}</div>}{a.attachmentUrl&&<a href={a.attachmentUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-black text-blue-600">Open assignment attachment</a>}</article>):<Empty text="No assignments published for this class."/>}</div></section>
   <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><h2 className="text-xl font-black">Learning materials</h2><div className="mt-4 space-y-3">{data.materials.length?data.materials.map(m=><div key={m.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-blue-600">{m.subject.name}</p><p className="mt-1 font-black">{m.title}</p>{m.description&&<p className="mt-1 text-sm text-slate-500">{m.description}</p>}<div className="mt-3 flex gap-3 text-xs font-black">{m.fileUrl&&<a href={m.fileUrl} target="_blank" rel="noreferrer" className="text-blue-600">Open file</a>}{m.externalUrl&&<a href={m.externalUrl} target="_blank" rel="noreferrer" className="text-violet-600">Open link</a>}</div></div>):<Empty text="No learning materials yet."/>}</div></article><article className="rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Syllabus progress</h2><p className="text-sm text-slate-500">{syllabusStats.done} of {syllabusStats.total} topics complete</p></div><span className="text-2xl font-black text-emerald-600">{syllabusStats.percent}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500" style={{width:`${syllabusStats.percent}%`}}/></div><div className="mt-4 space-y-2">{data.syllabus.length?data.syllabus.map(s=><div key={s.id} className="flex items-start gap-3 rounded-2xl bg-slate-50 p-3"><div className={`mt-0.5 grid h-7 w-7 place-items-center rounded-full ${s.isCompleted?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-500'}`}>{s.isCompleted?<CheckCircleRounded fontSize="small"/>:<ScheduleRounded fontSize="small"/>}</div><div><p className="text-xs font-black uppercase text-slate-400">{s.subject.name}</p><p className="font-bold">{s.title}</p>{s.description&&<p className="text-xs text-slate-500">{s.description}</p>}</div></div>):<Empty text="No syllabus topics configured."/>}</div></article></section>
  </>}
 </section></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <article className="rounded-[24px] border border-white bg-white/90 p-5 shadow-lg"><div className="inline-flex rounded-2xl bg-gradient-to-br from-violet-600 to-blue-500 p-2.5 text-white">{icon}</div><p className="mt-3 text-xs font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">{text}</div>}
