import { Router } from 'express';
import { Prisma, prisma } from '@nexora/database';
import { z } from 'zod';
import { requireAuth, requireRoles, requireTenant } from '../middleware/auth.js';

const router=Router();
router.use(requireAuth,requireTenant);

const timetableSchema=z.object({classId:z.string().uuid(),subjectId:z.string().uuid(),teacherId:z.string().uuid(),dayOfWeek:z.coerce.number().int().min(1).max(7),startsAt:z.string().regex(/^\d{2}:\d{2}$/),endsAt:z.string().regex(/^\d{2}:\d{2}$/),room:z.string().max(80).optional()});
router.get('/timetable',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT','PARENT'),async(req,res)=>{
 const schoolId=req.auth!.schoolId!; let classId=typeof req.query.classId==='string'?req.query.classId:undefined;
 if(req.auth!.role==='STUDENT'){const p=await prisma.studentProfile.findUnique({where:{userId:req.auth!.userId}});classId=p?.classId??undefined;}
 if(req.auth!.role==='TEACHER'){
  const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} AND t."teacherId"=${req.auth!.userId} ORDER BY t."dayOfWeek",t."startsAt"`);return res.json(rows);
 }
 const rows=classId?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} AND t."classId"=${classId} ORDER BY t."dayOfWeek",t."startsAt"`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} ORDER BY t."dayOfWeek",t."startsAt"`);
 res.json(rows);
});
router.post('/timetable',requireRoles('PRINCIPAL'),async(req,res)=>{const p=timetableSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid timetable entry'});const d=p.data,schoolId=req.auth!.schoolId!;const [c,s,t]=await Promise.all([prisma.class.findFirst({where:{id:d.classId,schoolId}}),prisma.subject.findFirst({where:{id:d.subjectId,schoolId}}),prisma.user.findFirst({where:{id:d.teacherId,schoolId,role:'TEACHER'}})]);if(!c||!s||!t)return res.status(400).json({message:'Invalid school class, subject or teacher'});const id=crypto.randomUUID(),now=new Date();await prisma.$executeRaw(Prisma.sql`INSERT INTO "TimetableEntry" ("id","schoolId","classId","subjectId","teacherId","dayOfWeek","startsAt","endsAt","room","createdAt","updatedAt") VALUES (${id},${schoolId},${d.classId},${d.subjectId},${d.teacherId},${d.dayOfWeek},${d.startsAt},${d.endsAt},${d.room??null},${now},${now})`);res.status(201).json({id,...d});});

const leaveSchema=z.object({fromDate:z.coerce.date(),toDate:z.coerce.date(),reason:z.string().min(3).max(2000)});
router.get('/leave',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!;const rows=req.auth!.role==='PRINCIPAL'?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT l.*,u."firstName",u."lastName",u.role FROM "LeaveRequest" l JOIN "User" u ON u.id=l."userId" WHERE l."schoolId"=${schoolId} ORDER BY l."createdAt" DESC`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "LeaveRequest" WHERE "schoolId"=${schoolId} AND "userId"=${req.auth!.userId} ORDER BY "createdAt" DESC`);res.json(rows);});
router.post('/leave',requireRoles('STAFF','TEACHER','STUDENT'),async(req,res)=>{const p=leaveSchema.safeParse(req.body);if(!p.success||p.data.toDate<p.data.fromDate)return res.status(400).json({message:'Invalid leave request'});const id=crypto.randomUUID(),now=new Date(),schoolId=req.auth!.schoolId!;await prisma.$executeRaw(Prisma.sql`INSERT INTO "LeaveRequest" ("id","schoolId","userId","fromDate","toDate","reason","status","createdAt","updatedAt") VALUES (${id},${schoolId},${req.auth!.userId},${p.data.fromDate},${p.data.toDate},${p.data.reason},'PENDING',${now},${now})`);res.status(201).json({id,status:'PENDING'});});
router.patch('/leave/:id/review',requireRoles('PRINCIPAL'),async(req,res)=>{const p=z.object({status:z.enum(['APPROVED','REJECTED']),remark:z.string().max(1000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid review'});const schoolId=req.auth!.schoolId!,now=new Date();await prisma.$executeRaw(Prisma.sql`UPDATE "LeaveRequest" SET "status"=${p.data.status},"reviewedById"=${req.auth!.userId},"reviewRemark"=${p.data.remark??null},"updatedAt"=${now} WHERE "id"=${req.params.id} AND "schoolId"=${schoolId}`);res.json({ok:true});});

router.get('/fees/summary',requireRoles('PRINCIPAL','STAFF'),async(req,res)=>{const schoolId=req.auth!.schoolId!,month=typeof req.query.month==='string'?req.query.month:new Date().toISOString().slice(0,7);const students=await prisma.studentProfile.findMany({where:{schoolId},select:{id:true,classId:true}});const structures=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "FeeStructure" WHERE "schoolId"=${schoolId}`);const payments=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "FeePayment" WHERE "schoolId"=${schoolId} AND "month"=${month}`);const map=new Map(structures.map(x=>[x.classId,Number(x.monthlyAmount)]));const expected=students.reduce((n,s)=>n+(s.classId?map.get(s.classId)??0:0),0);const collected=payments.reduce((n,p)=>n+Number(p.amount),0);res.json({month,expected,collected,pending:Math.max(0,expected-collected),paidStudents:payments.length,totalStudents:students.length});});
router.post('/fees/structure',requireRoles('PRINCIPAL'),async(req,res)=>{const p=z.object({classId:z.string().uuid(),monthlyAmount:z.coerce.number().positive(),currency:z.string().default('PKR')}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid fee structure'});const schoolId=req.auth!.schoolId!,id=crypto.randomUUID(),now=new Date();await prisma.$executeRaw(Prisma.sql`INSERT INTO "FeeStructure" ("id","schoolId","classId","monthlyAmount","currency","createdAt","updatedAt") VALUES (${id},${schoolId},${p.data.classId},${p.data.monthlyAmount},${p.data.currency},${now},${now}) ON CONFLICT ("schoolId","classId") DO UPDATE SET "monthlyAmount"=EXCLUDED."monthlyAmount","currency"=EXCLUDED."currency","updatedAt"=${now}`);res.json({ok:true});});
router.post('/fees/payment',requireRoles('PRINCIPAL','STAFF'),async(req,res)=>{const p=z.object({studentProfileId:z.string().uuid(),month:z.string().regex(/^\d{4}-\d{2}$/),amount:z.coerce.number().positive(),method:z.string().optional(),reference:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid payment'});const schoolId=req.auth!.schoolId!,student=await prisma.studentProfile.findFirst({where:{id:p.data.studentProfileId,schoolId}});if(!student)return res.status(404).json({message:'Student not found'});const id=crypto.randomUUID(),now=new Date();await prisma.$executeRaw(Prisma.sql`INSERT INTO "FeePayment" ("id","schoolId","studentProfileId","month","amount","status","method","reference","markedById","paidAt","createdAt") VALUES (${id},${schoolId},${p.data.studentProfileId},${p.data.month},${p.data.amount},'PAID',${p.data.method??null},${p.data.reference??null},${req.auth!.userId},${now},${now}) ON CONFLICT ("schoolId","studentProfileId","month") DO UPDATE SET "amount"=EXCLUDED."amount","status"='PAID',"method"=EXCLUDED."method","reference"=EXCLUDED."reference","markedById"=${req.auth!.userId},"paidAt"=${now}`);res.json({ok:true});});

export default router;