import { Router } from 'express';
import { Prisma, prisma } from '@nexora/database';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { requireAuth, requireRoles, requireTenant } from '../middleware/auth.js';
const router=Router();router.use(requireAuth,requireTenant);
const monthRe=/^\d{4}-\d{2}$/;
const adjustmentSchema=z.object({studentProfileId:z.string().uuid(),month:z.string().regex(monthRe),type:z.enum(['DISCOUNT','SCHOLARSHIP','FINE','WAIVER']),amount:z.coerce.number().positive(),reason:z.string().max(500).optional()});

router.post('/adjustments',requireRoles('PRINCIPAL'),async(req,res)=>{const parsed=adjustmentSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({message:'Invalid fee adjustment',issues:parsed.error.issues});const schoolId=req.auth!.schoolId!,x=parsed.data;const student=await prisma.studentProfile.findFirst({where:{id:x.studentProfileId,schoolId}});if(!student)return res.status(404).json({message:'Student not found'});const id=randomUUID();await prisma.$executeRaw(Prisma.sql`INSERT INTO "FeeAdjustment" (id,"schoolId","studentProfileId","month",type,amount,reason,"createdById") VALUES (${id},${schoolId},${x.studentProfileId},${x.month},${x.type},${x.amount},${x.reason??null},${req.auth!.userId})`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'FEE_ADJUSTMENT_CREATED',entityType:'FeeAdjustment',entityId:id,afterData:{...x} as any}});res.status(201).json({id,...x});});

router.get('/adjustments/:studentProfileId',requireRoles('PRINCIPAL','STAFF','STUDENT','PARENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!,student=await prisma.studentProfile.findFirst({where:{id:req.params.studentProfileId,schoolId}});if(!student)return res.status(404).json({message:'Student not found'});if(req.auth!.role==='STUDENT'&&student.userId!==req.auth!.userId)return res.status(403).json({message:'Forbidden'});if(req.auth!.role==='PARENT'){const p=await prisma.parentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});if(!p||!await prisma.studentParent.findFirst({where:{parentId:p.id,studentId:student.id}}))return res.status(403).json({message:'Forbidden'});}const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT fa.*,u."firstName",u."lastName" FROM "FeeAdjustment" fa JOIN "User" u ON u.id=fa."createdById" WHERE fa."schoolId"=${schoolId} AND fa."studentProfileId"=${student.id} ORDER BY fa."month" DESC,fa."createdAt" DESC`);res.json(rows.map(x=>({...x,amount:Number(x.amount),createdBy:`${x.firstName} ${x.lastName}`})));});

router.patch('/structure/:classId/settings',requireRoles('PRINCIPAL'),async(req,res)=>{const schema=z.object({dueDay:z.coerce.number().int().min(1).max(28),lateFineAmount:z.coerce.number().min(0),lateFineGraceDays:z.coerce.number().int().min(0).max(30)});const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid fee settings'});const schoolId=req.auth!.schoolId!;await prisma.$executeRaw(Prisma.sql`UPDATE "FeeStructure" SET "dueDay"=${p.data.dueDay},"lateFineAmount"=${p.data.lateFineAmount},"lateFineGraceDays"=${p.data.lateFineGraceDays},"updatedAt"=NOW() WHERE "schoolId"=${schoolId} AND "classId"=${req.params.classId}`);res.json({ok:true,...p.data});});

router.get('/student-balance/:studentProfileId',requireRoles('PRINCIPAL','STAFF','STUDENT','PARENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!,month=typeof req.query.month==='string'&&monthRe.test(req.query.month)?req.query.month:new Date().toISOString().slice(0,7);const student=await prisma.studentProfile.findFirst({where:{id:req.params.studentProfileId,schoolId}});if(!student)return res.status(404).json({message:'Student not found'});if(req.auth!.role==='STUDENT'&&student.userId!==req.auth!.userId)return res.status(403).json({message:'Forbidden'});if(req.auth!.role==='PARENT'){const p=await prisma.parentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});if(!p||!await prisma.studentParent.findFirst({where:{parentId:p.id,studentId:student.id}}))return res.status(403).json({message:'Forbidden'});}const [fs,pay,adj]=await Promise.all([student.classId?prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "FeeStructure" WHERE "schoolId"=${schoolId} AND "classId"=${student.classId} LIMIT 1`):Promise.resolve([]),prisma.$queryRaw<any[]>(Prisma.sql`SELECT COALESCE(SUM(amount),0) total FROM "FeePayment" WHERE "schoolId"=${schoolId} AND "studentProfileId"=${student.id} AND month=${month} AND "approvalStatus"<>'REJECTED'`),prisma.$queryRaw<any[]>(Prisma.sql`SELECT type,COALESCE(SUM(amount),0) total FROM "FeeAdjustment" WHERE "schoolId"=${schoolId} AND "studentProfileId"=${student.id} AND month=${month} GROUP BY type`)]);const base=Number(fs[0]?.monthlyAmount??0),dueDay=Number(fs[0]?.dueDay??10),grace=Number(fs[0]?.lateFineGraceDays??0),fineSetting=Number(fs[0]?.lateFineAmount??0),m=new Map(adj.map(x=>[x.type,Number(x.total)])),discount=(m.get('DISCOUNT')??0)+(m.get('SCHOLARSHIP')??0)+(m.get('WAIVER')??0),manualFine=m.get('FINE')??0;const [y,mo]=month.split('-').map(Number),autoFine=new Date()>new Date(y,mo-1,dueDay+grace,23,59,59)?fineSetting:0,expected=Math.max(0,base-discount+manualFine+autoFine),paid=Number(pay[0]?.total??0);res.json({month,baseFee:base,discount,manualFine,autoFine,expected,paid,balance:Math.max(0,expected-paid),status:paid<=0?'UNPAID':paid<expected?'PARTIAL':'PAID',dueDay});});

router.post('/send-overdue-notifications',requireRoles('PRINCIPAL'),async(req,res)=>{const schoolId=req.auth!.schoolId!,month=typeof req.body?.month==='string'&&monthRe.test(req.body.month)?req.body.month:new Date().toISOString().slice(0,7);const students=await prisma.studentProfile.findMany({where:{schoolId,classId:{not:null}},include:{user:true,parentLinks:{include:{parent:{include:{user:true}}}}}});let sent=0;for(const s of students){const fs=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT "monthlyAmount" FROM "FeeStructure" WHERE "schoolId"=${schoolId} AND "classId"=${s.classId!} LIMIT 1`);if(!fs[0])continue;const paid=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT COALESCE(SUM(amount),0) total FROM "FeePayment" WHERE "schoolId"=${schoolId} AND "studentProfileId"=${s.id} AND month=${month} AND "approvalStatus"<>'REJECTED'`);if(Number(paid[0]?.total??0)>=Number(fs[0].monthlyAmount))continue;const recipients=[s.user,...s.parentLinks.map(l=>l.parent.user)];for(const u of recipients){await prisma.notification.create({data:{schoolId,userId:u.id,title:'Fee payment reminder',body:`Fee for ${month} is still outstanding for ${s.user.firstName} ${s.user.lastName}. Please contact the school finance office.`,link:u.role==='PARENT'?`/parent/fees?studentProfileId=${s.id}`:'/student/fees'}});sent++;}}res.json({ok:true,month,notificationsSent:sent});});
export default router;