import { randomUUID } from 'node:crypto';
import { Router } from 'express';
import { Prisma, prisma } from '@nexora/database';
import { z } from 'zod';
import { requireAuth,requireRoles,requireTenant } from '../middleware/auth.js';
import { routeParam } from '../utils/http.js';
const router=Router();router.use(requireAuth,requireTenant);
const leaveSchema=z.object({fromDate:z.coerce.date(),toDate:z.coerce.date(),reason:z.string().min(3).max(2000)});
router.get('/leave',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!;const rows=req.auth!.role==='PRINCIPAL'?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT l.*,u."firstName",u."lastName",u.role FROM "LeaveRequest" l JOIN "User" u ON u.id=l."userId" WHERE l."schoolId"=${schoolId} ORDER BY CASE WHEN l.status='PENDING' THEN 0 ELSE 1 END,l."createdAt" DESC`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "LeaveRequest" WHERE "schoolId"=${schoolId} AND "userId"=${req.auth!.userId} ORDER BY "createdAt" DESC`);res.json(rows);});
router.post('/leave',requireRoles('STAFF','TEACHER','STUDENT'),async(req,res)=>{const p=leaveSchema.safeParse(req.body);if(!p.success||p.data.toDate<p.data.fromDate)return res.status(400).json({message:'Invalid leave request'});const schoolId=req.auth!.schoolId!,now=new Date();const overlap=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM "LeaveRequest" WHERE "schoolId"=${schoolId} AND "userId"=${req.auth!.userId} AND status IN ('PENDING','APPROVED') AND "fromDate"<=${p.data.toDate} AND "toDate">=${p.data.fromDate} LIMIT 1`);if(overlap[0])return res.status(409).json({message:'You already have an overlapping leave request'});const id=randomUUID();await prisma.$executeRaw(Prisma.sql`INSERT INTO "LeaveRequest" (id,"schoolId","userId","fromDate","toDate",reason,status,"createdAt","updatedAt") VALUES (${id},${schoolId},${req.auth!.userId},${p.data.fromDate},${p.data.toDate},${p.data.reason},'PENDING',${now},${now})`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'LEAVE_REQUESTED',entityType:'LeaveRequest',entityId:id,afterData:{fromDate:p.data.fromDate,toDate:p.data.toDate,reason:p.data.reason}}});const principals=await prisma.user.findMany({where:{schoolId,role:'PRINCIPAL',isActive:true},select:{id:true}});for(const x of principals)await prisma.notification.create({data:{schoolId,userId:x.id,title:'New leave request',body:'A new leave request is waiting for review.',link:'/principal/leave'}});res.status(201).json({id,status:'PENDING'});});
router.patch('/leave/:id/review',requireRoles('PRINCIPAL'),async(req,res)=>{const p=z.object({status:z.enum(['APPROVED','REJECTED']),remark:z.string().max(1000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid review'});const id=routeParam(req.params.id),schoolId=req.auth!.schoolId!,now=new Date();const row=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT l.*,u.role as "userRole" FROM "LeaveRequest" l JOIN "User" u ON u.id=l."userId" WHERE l.id=${id} AND l."schoolId"=${schoolId} AND l.status='PENDING' LIMIT 1`))[0];if(!row)return res.status(404).json({message:'Pending leave request not found'});await prisma.$executeRaw(Prisma.sql`UPDATE "LeaveRequest" SET status=${p.data.status},"reviewedById"=${req.auth!.userId},"reviewRemark"=${p.data.remark??null},"updatedAt"=${now} WHERE id=${id} AND "schoolId"=${schoolId}`);const rolePath=String(row.userRole).toLowerCase();await prisma.notification.create({data:{schoolId,userId:row.userId,title:`Leave ${p.data.status.toLowerCase()}`,body:p.data.remark?`Principal remark: ${p.data.remark}`:`Your leave request has been ${p.data.status.toLowerCase()}.`,link:`/${rolePath}/leave`}});await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:`LEAVE_${p.data.status}`,entityType:'LeaveRequest',entityId:id,beforeData:row,afterData:{status:p.data.status,remark:p.data.remark??null}}});res.json({ok:true});});

const eventSchema=z.object({title:z.string().min(2).max(180),description:z.string().max(2000).optional(),eventType:z.enum(['GENERAL','HOLIDAY','EXAM','MEETING','TOUR','SPORTS','DEADLINE','CEREMONY']).default('GENERAL'),startsAt:z.coerce.date(),endsAt:z.coerce.date().optional(),audience:z.enum(['ALL','STAFF','TEACHER','STUDENT','PARENT']).default('ALL'),classId:z.string().uuid().optional(),location:z.string().max(180).optional(),isAllDay:z.boolean().default(false)});
router.get('/events',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT','PARENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!,from=typeof req.query.from==='string'?new Date(req.query.from):new Date(Date.now()-30*86400000),to=typeof req.query.to==='string'?new Date(req.query.to):new Date(Date.now()+180*86400000);let classId:string|undefined;if(req.auth!.role==='STUDENT'){const s=await prisma.studentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});classId=s?.classId??undefined;}if(req.auth!.role==='PARENT'){const studentId=typeof req.query.studentId==='string'?req.query.studentId:undefined;if(studentId){const p=await prisma.parentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});const link=p?await prisma.studentParent.findFirst({where:{parentId:p.id,studentId}}):null;if(!link)return res.status(403).json({message:'Child not linked'});const s=await prisma.studentProfile.findFirst({where:{schoolId,id:studentId}});classId=s?.classId??undefined;}}const role=req.auth!.role;const rows=classId?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT e.*,u."firstName",u."lastName" FROM "SchoolEvent" e JOIN "User" u ON u.id=e."createdById" WHERE e."schoolId"=${schoolId} AND e."startsAt" BETWEEN ${from} AND ${to} AND (e.audience='ALL' OR e.audience=${role}) AND (e."classId" IS NULL OR e."classId"=${classId}) ORDER BY e."startsAt"`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT e.*,u."firstName",u."lastName" FROM "SchoolEvent" e JOIN "User" u ON u.id=e."createdById" WHERE e."schoolId"=${schoolId} AND e."startsAt" BETWEEN ${from} AND ${to} AND (e.audience='ALL' OR e.audience=${role}) ORDER BY e."startsAt"`);res.json(rows);});
router.post('/events',requireRoles('PRINCIPAL'),async(req,res)=>{const p=eventSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid event'});const d=p.data,schoolId=req.auth!.schoolId!;if(d.endsAt&&d.endsAt<d.startsAt)return res.status(400).json({message:'Event end must be after start'});if(d.classId&&!await prisma.class.findFirst({where:{id:d.classId,schoolId}}))return res.status(400).json({message:'Invalid class'});const id=randomUUID(),now=new Date();await prisma.$executeRaw(Prisma.sql`INSERT INTO "SchoolEvent" (id,"schoolId","createdById",title,description,"eventType","startsAt","endsAt",audience,"classId",location,"isAllDay","createdAt","updatedAt") VALUES (${id},${schoolId},${req.auth!.userId},${d.title},${d.description??null},${d.eventType},${d.startsAt},${d.endsAt??null},${d.audience},${d.classId??null},${d.location??null},${d.isAllDay},${now},${now})`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'SCHOOL_EVENT_CREATED',entityType:'SchoolEvent',entityId:id,afterData:d as any}});res.status(201).json({id,...d});});
router.delete('/events/:id',requireRoles('PRINCIPAL'),async(req,res)=>{const id=routeParam(req.params.id),schoolId=req.auth!.schoolId!,old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "SchoolEvent" WHERE id=${id} AND "schoolId"=${schoolId} LIMIT 1`))[0];if(!old)return res.status(404).json({message:'Event not found'});await prisma.$executeRaw(Prisma.sql`DELETE FROM "SchoolEvent" WHERE id=${id} AND "schoolId"=${schoolId}`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'SCHOOL_EVENT_DELETED',entityType:'SchoolEvent',entityId:id,beforeData:old}});res.json({ok:true});});
export default router;