import { randomUUID } from 'node:crypto';
import { Router, raw } from 'express';
import { Prisma, prisma } from '@nexora/database';
import { z } from 'zod';
import { requireAuth, requireRoles, requireTenant } from '../middleware/auth.js';

const router=Router();
router.use(requireAuth,requireTenant);
const bucket='nexora-private';
const allowed=new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain','text/csv','image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','application/zip']);
const categories=new Set(['school-logo','assignment','material','submission','exam','report','general']);
function env(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase storage environment is not configured');return{url:url.replace(/\/$/,''),key};}
async function ensureBucket(){const {url,key}=env();const headers={Authorization:`Bearer ${key}`,apikey:key,'Content-Type':'application/json'};const check=await fetch(`${url}/storage/v1/bucket/${bucket}`,{headers});if(check.ok)return;const create=await fetch(`${url}/storage/v1/bucket`,{method:'POST',headers,body:JSON.stringify({id:bucket,name:bucket,public:false,file_size_limit:104857600,allowed_mime_types:[...allowed]})});if(!create.ok&&create.status!==409)throw new Error(`Could not initialize storage bucket: ${await create.text()}`);}
const clean=(name:string)=>name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'-').replace(/-+/g,'-').slice(-120)||'file';

router.post('/upload',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT'),raw({type:'application/octet-stream',limit:'100mb'}),async(req,res)=>{
 const q=z.object({fileName:z.string().min(1).max(180),mimeType:z.string().min(1).max(150),category:z.string().min(1).max(40)}).safeParse(req.query);if(!q.success)return res.status(400).json({message:'Invalid upload metadata'});const {fileName,mimeType,category}=q.data;if(!allowed.has(mimeType))return res.status(415).json({message:'File type is not allowed'});if(!categories.has(category))return res.status(400).json({message:'Invalid file category'});if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({message:'Empty file'});
 const schoolId=req.auth!.schoolId!,school=await prisma.school.findUnique({where:{id:schoolId},select:{storageLimitMb:true}});if(!school)return res.status(404).json({message:'School not found'});const usage=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT COALESCE(SUM("sizeBytes"),0) total FROM "StorageObject" WHERE "schoolId"=${schoolId}`);const used=Number(usage[0]?.total??0),limit=school.storageLimitMb*1024*1024;if(used+req.body.length>limit)return res.status(413).json({message:'School storage quota exceeded',usedBytes:used,limitBytes:limit});
 await ensureBucket();const id=randomUUID(),path=`${schoolId}/${category}/${new Date().getUTCFullYear()}/${id}-${clean(fileName)}`;const {url,key}=env();const upload=await fetch(`${url}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':mimeType,'x-upsert':'false'},body:req.body});if(!upload.ok)return res.status(502).json({message:'Storage upload failed',detail:(await upload.text()).slice(0,300)});
 await prisma.$executeRaw(Prisma.sql`INSERT INTO "StorageObject" (id,"schoolId","uploadedById",bucket,path,"originalName","mimeType","sizeBytes",category) VALUES (${id},${schoolId},${req.auth!.userId},${bucket},${path},${fileName},${mimeType},${req.body.length},${category})`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'FILE_UPLOADED',entityType:'StorageObject',entityId:id,afterData:{fileName,mimeType,sizeBytes:req.body.length,category}}});res.status(201).json({id,reference:`storage://${id}`,fileName,mimeType,sizeBytes:req.body.length,category});
});

router.post('/sign',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT','PARENT'),async(req,res)=>{const p=z.object({reference:z.string().regex(/^storage:\/\/[0-9a-f-]+$/i)}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid storage reference'});const id=p.data.reference.slice('storage://'.length),schoolId=req.auth!.schoolId!;const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "StorageObject" WHERE id=${id} AND "schoolId"=${schoolId} LIMIT 1`);const obj=rows[0];if(!obj)return res.status(404).json({message:'File not found'});const {url,key}=env();const sign=await fetch(`${url}/storage/v1/object/sign/${obj.bucket}/${obj.path}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:900})});if(!sign.ok)return res.status(502).json({message:'Could not create download link'});const data:any=await sign.json();const signed=data.signedURL||data.signedUrl;res.json({url:signed?.startsWith('http')?signed:`${url}/storage/v1${signed}`,expiresIn:900,fileName:obj.originalName,mimeType:obj.mimeType,sizeBytes:Number(obj.sizeBytes)});});

router.delete('/:id',requireRoles('PRINCIPAL'),async(req,res)=>{const schoolId=req.auth!.schoolId!;const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "StorageObject" WHERE id=${req.params.id} AND "schoolId"=${schoolId} LIMIT 1`);const obj=rows[0];if(!obj)return res.status(404).json({message:'File not found'});const {url,key}=env();const del=await fetch(`${url}/storage/v1/object/${obj.bucket}/${obj.path}`,{method:'DELETE',headers:{Authorization:`Bearer ${key}`,apikey:key}});if(!del.ok&&del.status!==404)return res.status(502).json({message:'Could not delete storage object'});await prisma.$executeRaw(Prisma.sql`DELETE FROM "StorageObject" WHERE id=${obj.id} AND "schoolId"=${schoolId}`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'FILE_DELETED',entityType:'StorageObject',entityId:obj.id,beforeData:{fileName:obj.originalName,category:obj.category}}});res.json({ok:true});});

router.get('/usage',requireRoles('PRINCIPAL','STAFF'),async(req,res)=>{const schoolId=req.auth!.schoolId!,school=await prisma.school.findUnique({where:{id:schoolId},select:{storageLimitMb:true}});const usage=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT COALESCE(SUM("sizeBytes"),0) bytes,COUNT(*) files FROM "StorageObject" WHERE "schoolId"=${schoolId}`);const usedBytes=Number(usage[0]?.bytes??0),limitBytes=(school?.storageLimitMb??0)*1024*1024;res.json({usedBytes,limitBytes,files:Number(usage[0]?.files??0),percentage:limitBytes?Math.round(usedBytes/limitBytes*1000)/10:0});});
export default router;