import { randomUUID } from 'node:crypto';
import { Router } from 'express';
import { Prisma,prisma } from '@nexora/database';
import { z } from 'zod';
import { requireAuth,requireRoles } from '../middleware/auth.js';
import { routeParam } from '../utils/http.js';

const router=Router();router.use(requireAuth);
const createSchema=z.object({subject:z.string().min(4).max(180),category:z.enum(['GENERAL','BILLING','TECHNICAL','DATA','ACCOUNT','FEATURE']).default('GENERAL'),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL'),message:z.string().min(4).max(5000)});
router.post('/tickets',requireRoles('PRINCIPAL','STAFF'),async(req,res)=>{const p=createSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid support ticket',issues:p.error.flatten()});const schoolId=req.auth!.schoolId;if(!schoolId)return res.status(403).json({message:'School scope required'});const id=randomUUID(),messageId=randomUUID(),now=new Date();await prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`INSERT INTO "SupportTicket" (id,"schoolId","createdById",subject,category,priority,status,"createdAt","updatedAt") VALUES (${id},${schoolId},${req.auth!.userId},${p.data.subject},${p.data.category},${p.data.priority},'OPEN',${now},${now})`);await tx.$executeRaw(Prisma.sql`INSERT INTO "SupportTicketMessage" (id,"ticketId","authorId",body,"isInternal","createdAt") VALUES (${messageId},${id},${req.auth!.userId},${p.data.message},false,${now})`);await tx.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'SUPPORT_TICKET_CREATED',entityType:'SupportTicket',entityId:id,afterData:{subject:p.data.subject,category:p.data.category,priority:p.data.priority}}})});res.status(201).json({id,status:'OPEN'})});

router.get('/tickets',requireRoles('SUPER_ADMIN','PRINCIPAL','STAFF'),async(req,res)=>{const status=typeof req.query.status==='string'?req.query.status:undefined;if(req.auth!.role==='SUPER_ADMIN'){const rows=status?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,s.name as "schoolName",u."firstName",u."lastName",(SELECT COUNT(*) FROM "SupportTicketMessage" m WHERE m."ticketId"=t.id) as "messageCount" FROM "SupportTicket" t JOIN "School" s ON s.id=t."schoolId" JOIN "User" u ON u.id=t."createdById" WHERE t.status=${status} ORDER BY CASE t.priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,t."updatedAt" DESC`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,s.name as "schoolName",u."firstName",u."lastName",(SELECT COUNT(*) FROM "SupportTicketMessage" m WHERE m."ticketId"=t.id) as "messageCount" FROM "SupportTicket" t JOIN "School" s ON s.id=t."schoolId" JOIN "User" u ON u.id=t."createdById" ORDER BY CASE t.status WHEN 'OPEN' THEN 0 WHEN 'IN_PROGRESS' THEN 1 WHEN 'WAITING_ON_SCHOOL' THEN 2 WHEN 'RESOLVED' THEN 3 ELSE 4 END,CASE t.priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,t."updatedAt" DESC`);return res.json(rows.map(x=>({...x,messageCount:Number(x.messageCount??0)}))}const schoolId=req.auth!.schoolId!;const rows=status?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,u."firstName",u."lastName",(SELECT COUNT(*) FROM "SupportTicketMessage" m WHERE m."ticketId"=t.id AND m."isInternal"=false) as "messageCount" FROM "SupportTicket" t JOIN "User" u ON u.id=t."createdById" WHERE t."schoolId"=${schoolId} AND t.status=${status} ORDER BY t."updatedAt" DESC`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,u."firstName",u."lastName",(SELECT COUNT(*) FROM "SupportTicketMessage" m WHERE m."ticketId"=t.id AND m."isInternal"=false) as "messageCount" FROM "SupportTicket" t JOIN "User" u ON u.id=t."createdById" WHERE t."schoolId"=${schoolId} ORDER BY t."updatedAt" DESC`);res.json(rows.map(x=>({...x,messageCount:Number(x.messageCount??0)}))});

router.get('/tickets/:id',requireRoles('SUPER_ADMIN','PRINCIPAL','STAFF'),async(req,res)=>{const id=routeParam(req.params.id);const tickets=req.auth!.role==='SUPER_ADMIN'?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,s.name as "schoolName" FROM "SupportTicket" t JOIN "School" s ON s.id=t."schoolId" WHERE t.id=${id} LIMIT 1`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.* FROM "SupportTicket" t WHERE t.id=${id} AND t."schoolId"=${req.auth!.schoolId!} LIMIT 1`);const ticket=tickets[0];if(!ticket)return res.status(404).json({message:'Support ticket not found'});const messages=req.auth!.role==='SUPER_ADMIN'?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT m.*,u."firstName",u."lastName",u.role FROM "SupportTicketMessage" m JOIN "User" u ON u.id=m."authorId" WHERE m."ticketId"=${id} ORDER BY m."createdAt"`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT m.*,u."firstName",u."lastName",u.role FROM "SupportTicketMessage" m JOIN "User" u ON u.id=m."authorId" WHERE m."ticketId"=${id} AND m."isInternal"=false ORDER BY m."createdAt"`);res.json({ticket,messages})});

const messageSchema=z.object({body:z.string().min(1).max(5000),isInternal:z.boolean().default(false)});
router.post('/tickets/:id/messages',requireRoles('SUPER_ADMIN','PRINCIPAL','STAFF'),async(req,res)=>{const p=messageSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid reply'});if(p.data.isInternal&&req.auth!.role!=='SUPER_ADMIN')return res.status(403).json({message:'Internal notes are Super Admin only'});const id=routeParam(req.params.id);const rows=req.auth!.role==='SUPER_ADMIN'?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "SupportTicket" WHERE id=${id} LIMIT 1`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "SupportTicket" WHERE id=${id} AND "schoolId"=${req.auth!.schoolId!} LIMIT 1`);const ticket=rows[0];if(!ticket)return res.status(404).json({message:'Support ticket not found'});if(['RESOLVED','CLOSED'].includes(ticket.status)&&req.auth!.role!=='SUPER_ADMIN')return res.status(409).json({message:'Resolved or closed tickets cannot be replied to'});const messageId=randomUUID(),now=new Date(),nextStatus=req.auth!.role==='SUPER_ADMIN'&&!p.data.isInternal?'WAITING_ON_SCHOOL':req.auth!.role==='SUPER_ADMIN'?ticket.status:'OPEN';await prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`INSERT INTO "SupportTicketMessage" (id,"ticketId","authorId",body,"isInternal","createdAt") VALUES (${messageId},${id},${req.auth!.userId},${p.data.body},${p.data.isInternal},${now})`);await tx.$executeRaw(Prisma.sql`UPDATE "SupportTicket" SET status=${nextStatus},"updatedAt"=${now} WHERE id=${id}`);await tx.auditLog.create({data:{schoolId:ticket.schoolId,actorId:req.auth!.userId,action:p.data.isInternal?'SUPPORT_INTERNAL_NOTE_ADDED':'SUPPORT_REPLY_ADDED',entityType:'SupportTicket',entityId:id,afterData:{messageId,status:nextStatus}}});if(req.auth!.role==='SUPER_ADMIN'&&!p.data.isInternal){const users=await tx.user.findMany({where:{schoolId:ticket.schoolId,role:{in:['PRINCIPAL','STAFF']},isActive:true},select:{id:true}});if(users.length)await tx.notification.createMany({data:users.map(u=>({schoolId:ticket.schoolId,userId:u.id,title:'Nexora Support replied',body:ticket.subject,link:'/support'}))})}});res.status(201).json({id:messageId,status:nextStatus})});

const updateSchema=z.object({status:z.enum(['OPEN','IN_PROGRESS','WAITING_ON_SCHOOL','RESOLVED','CLOSED']).optional(),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).optional(),assignedToId:z.string().uuid().nullable().optional()});
router.patch('/tickets/:id',requireRoles('SUPER_ADMIN'),async(req,res)=>{const p=updateSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid support update'});const id=routeParam(req.params.id),rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "SupportTicket" WHERE id=${id} LIMIT 1`),ticket=rows[0];if(!ticket)return res.status(404).json({message:'Support ticket not found'});if(p.data.assignedToId){const admin=await prisma.user.findFirst({where:{id:p.data.assignedToId,role:'SUPER_ADMIN',isActive:true}});if(!admin)return res.status(400).json({message:'Assignee must be an active Super Admin'})}const status=p.data.status??ticket.status,priority=p.data.priority??ticket.priority,assignedToId=p.data.assignedToId===undefined?ticket.assignedToId:p.data.assignedToId,now=new Date();await prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`UPDATE "SupportTicket" SET status=${status},priority=${priority},"assignedToId"=${assignedToId},"updatedAt"=${now} WHERE id=${id}`);await tx.auditLog.create({data:{schoolId:ticket.schoolId,actorId:req.auth!.userId,action:'SUPPORT_TICKET_UPDATED',entityType:'SupportTicket',entityId:id,beforeData:{status:ticket.status,priority:ticket.priority,assignedToId:ticket.assignedToId},afterData:{status,priority,assignedToId}}})});res.json({ok:true,status,priority,assignedToId})});

export default router;
