import { randomUUID } from 'node:crypto';
import { Router } from 'express';
import { Prisma, prisma } from '@nexora/database';
import { z } from 'zod';
import { requireAuth,requireRoles,requireTenant } from '../middleware/auth.js';
const router=Router();router.use(requireAuth,requireTenant);
const schema=z.object({classId:z.string().uuid(),subjectId:z.string().uuid(),teacherId:z.string().uuid(),dayOfWeek:z.coerce.number().int().min(1).max(7),startsAt:z.string().regex(/^\d{2}:\d{2}$/),endsAt:z.string().regex(/^\d{2}:\d{2}$/),room:z.string().trim().max(80).optional().nullable()});
async function validate(schoolId:string,d:any){if(d.startsAt>=d.endsAt)return 'End time must be after start time';const [c,s,t,a]=await Promise.all([prisma.class.findFirst({where:{id:d.classId,schoolId}}),prisma.subject.findFirst({where:{id:d.subjectId,schoolId}}),prisma.user.findFirst({where:{id:d.teacherId,schoolId,role:'TEACHER',isActive:true}}),prisma.teacherAssignment.findFirst({where:{schoolId,classId:d.classId,subjectId:d.subjectId,teacherId:d.teacherId}})]);if(!c||!s||!t)return 'Invalid class, subject or teacher';if(!a)return 'Teacher is not assigned to this class and subject';return null;}
async function conflict(schoolId:string,d:any,exclude?:string){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.id,c.name as "className",s.name as "subjectName",u."firstName",u."lastName",t.room FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} AND t."dayOfWeek"=${d.dayOfWeek} AND t."startsAt" < ${d.endsAt} AND t."endsAt" > ${d.startsAt} AND (${exclude??''}='' OR t.id<>${exclude??''}) AND (t."classId"=${d.classId} OR t."teacherId"=${d.teacherId} OR (${d.room??''}<>'' AND t.room=${d.room??''})) LIMIT 1`);return rows[0];}
router.get('/',requireRoles('PRINCIPAL','STAFF','TEACHER','STUDENT','PARENT'),async(req,res)=>{const schoolId=req.auth!.schoolId!;let classId=typeof req.query.classId==='string'?req.query.classId:undefined;if(req.auth!.role==='TEACHER'){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} AND t."teacherId"=${req.auth!.userId} ORDER BY t."dayOfWeek",t."startsAt"`);return res.json(rows);}if(req.auth!.role==='STUDENT'){const sp=await prisma.studentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});classId=sp?.classId??undefined;if(!classId)return res.json([]);}if(req.auth!.role==='PARENT'){const studentId=typeof req.query.studentId==='string'?req.query.studentId:undefined;if(!studentId)return res.status(400).json({message:'Select a linked child'});const pp=await prisma.parentProfile.findFirst({where:{schoolId,userId:req.auth!.userId}});const link=pp?await prisma.studentParent.findFirst({where:{parentId:pp.id,studentId}}):null;if(!link)return res.status(403).json({message:'Child is not linked to this parent'});const sp=await prisma.studentProfile.findFirst({where:{schoolId,id:studentId}});classId=sp?.classId??undefined;if(!classId)return res.json([]);}const rows=classId?await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} AND t."classId"=${classId} ORDER BY t."dayOfWeek",t."startsAt"`):await prisma.$queryRaw<any[]>(Prisma.sql`SELECT t.*,c.name as "className",c.section,s.name as "subjectName",u."firstName",u."lastName" FROM "TimetableEntry" t JOIN "Class" c ON c.id=t."classId" JOIN "Subject" s ON s.id=t."subjectId" JOIN "User" u ON u.id=t."teacherId" WHERE t."schoolId"=${schoolId} ORDER BY t."dayOfWeek",t."startsAt"`);res.json(rows);});
router.post('/',requireRoles('PRINCIPAL'),async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid timetable entry'});const schoolId=req.auth!.schoolId!,d=p.data,err=await validate(schoolId,d);if(err)return res.status(400).json({message:err});const hit=await conflict(schoolId,d);if(hit)return res.status(409).json({message:`Schedule conflict with ${hit.subjectName} / ${hit.className}`,conflict:hit});const id=randomUUID(),now=new Date();await prisma.$executeRaw(Prisma.sql`INSERT INTO "TimetableEntry" (id,"schoolId","classId","subjectId","teacherId","dayOfWeek","startsAt","endsAt",room,"createdAt","updatedAt") VALUES (${id},${schoolId},${d.classId},${d.subjectId},${d.teacherId},${d.dayOfWeek},${d.startsAt},${d.endsAt},${d.room??null},${now},${now})`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'TIMETABLE_CREATED',entityType:'TimetableEntry',entityId:id,afterData:d as any}});res.status(201).json({id,...d});});
router.put('/:id',requireRoles('PRINCIPAL'),async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid timetable entry'});const schoolId=req.auth!.schoolId!,d=p.data,old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "TimetableEntry" WHERE id=${req.params.id} AND "schoolId"=${schoolId} LIMIT 1`))[0];if(!old)return res.status(404).json({message:'Entry not found'});const err=await validate(schoolId,d);if(err)return res.status(400).json({message:err});const hit=await conflict(schoolId,d,req.params.id);if(hit)return res.status(409).json({message:`Schedule conflict with ${hit.subjectName} / ${hit.className}`});await prisma.$executeRaw(Prisma.sql`UPDATE "TimetableEntry" SET "classId"=${d.classId},"subjectId"=${d.subjectId},"teacherId"=${d.teacherId},"dayOfWeek"=${d.dayOfWeek},"startsAt"=${d.startsAt},"endsAt"=${d.endsAt},room=${d.room??null},"updatedAt"=${new Date()} WHERE id=${req.params.id} AND "schoolId"=${schoolId}`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'TIMETABLE_UPDATED',entityType:'TimetableEntry',entityId:req.params.id,beforeData:old,afterData:d as any}});res.json({ok:true});});
router.delete('/:id',requireRoles('PRINCIPAL'),async(req,res)=>{const schoolId=req.auth!.schoolId!,old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "TimetableEntry" WHERE id=${req.params.id} AND "schoolId"=${schoolId} LIMIT 1`))[0];if(!old)return res.status(404).json({message:'Entry not found'});await prisma.$executeRaw(Prisma.sql`DELETE FROM "TimetableEntry" WHERE id=${req.params.id} AND "schoolId"=${schoolId}`);await prisma.auditLog.create({data:{schoolId,actorId:req.auth!.userId,action:'TIMETABLE_DELETED',entityType:'TimetableEntry',entityId:req.params.id,beforeData:old}});res.json({ok:true});});
export default router;