import { AccountBalanceWalletRounded, CampaignRounded, CalendarMonthRounded, ClassRounded, FactCheckRounded, GroupsRounded, NotificationsRounded, ScheduleRounded } from '@mui/icons-material';
import { Alert, Skeleton } from '@mui/material';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../lib/api';

type Request = { id:string; requestType:string; status:string; principalRemark?:string|null; updatedAt:string };
type Announcement = { id:string; title:string; body:string; isPinned:boolean; createdAt:string };
type Batch = { id:string; status:string; totalAmount:number; studentCount:number; createdAt:string; submittedAt?:string|null } | null;
type Dashboard = { students:number; classes:number; myPendingRequests:number; unreadNotifications:number; announcements:Announcement[]; recentRequests:Request[]; openBatch:Batch };

const money=(value:number)=>`Rs ${Number(value||0).toLocaleString('en-PK')}`;

export default function StaffDashboard(){
 const [data,setData]=useState<Dashboard|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{api.get<Dashboard>('/dashboard/staff').then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.message??'Could not load Staff workspace.')).finally(()=>setLoading(false));},[]);
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#edf5ff,transparent_32%),radial-gradient(circle_at_top_right,#fff4e8,transparent_30%),#f8faff] p-4 md:p-8"><section className="mx-auto max-w-7xl">
  <header className="rounded-[34px] border border-white bg-white/88 p-6 shadow-[0_30px_90px_rgba(80,95,140,.14)] backdrop-blur-xl md:p-8"><p className="text-xs font-black uppercase tracking-[.22em] text-blue-600">Staff operations</p><h1 className="mt-2 text-3xl font-black text-slate-950 md:text-5xl">Daily school work, in one place.</h1><p className="mt-3 max-w-3xl text-sm text-slate-500 md:text-base">Handle student operations, approval requests, fee recovery, timetable and school-day workflows without crossing Principal-only controls.</p></header>
  {error&&<Alert severity="error" className="mt-5">{error}</Alert>}
  {loading?<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4,5,6,7,8].map(i=><Skeleton key={i} height={130} variant="rounded" sx={{borderRadius:5}}/>)}</div>:data&&<>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<GroupsRounded/>} label="Students" value={data.students}/><Metric icon={<ClassRounded/>} label="Classes" value={data.classes}/><Metric icon={<FactCheckRounded/>} label="My pending requests" value={data.myPendingRequests}/><Metric icon={<NotificationsRounded/>} label="Unread notifications" value={data.unreadNotifications}/></section>
   <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><Quick to="/staff/requests" icon={<FactCheckRounded/>} title="Requests" note="Approval workflow"/><Quick to="/staff/fees" icon={<AccountBalanceWalletRounded/>} title="Fees" note="Receive & hand over"/><Quick to="/staff/timetable" icon={<ScheduleRounded/>} title="Timetable" note="School schedules"/><Quick to="/staff/leave" icon={<CalendarMonthRounded/>} title="Leave" note="My requests"/><Quick to="/staff/calendar" icon={<CalendarMonthRounded/>} title="Calendar" note="Events & dates"/><Quick to="/staff/announcements" icon={<CampaignRounded/>} title="Announcements" note="School updates"/></section>
   <section className="mt-6 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
    <article className="rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-600">Fee accountability</p><h2 className="mt-1 text-xl font-black">My current cash batch</h2></div><AccountBalanceWalletRounded className="text-emerald-600"/></div>{data.openBatch?<div className="mt-5 rounded-[22px] bg-gradient-to-br from-emerald-50 to-cyan-50 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-3xl font-black text-slate-950">{money(data.openBatch.totalAmount)}</p><p className="mt-1 text-sm text-slate-500">{data.openBatch.studentCount} students represented</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${data.openBatch.status==='SUBMITTED'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{data.openBatch.status}</span></div><Link to="/staff/fees" className="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white">Open recovery center</Link></div>:<div className="mt-5 rounded-[22px] border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No open or submitted cash batch. Receiving a fee installment will create one.</div>}</article>
    <article className="rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><h2 className="text-xl font-black">My recent approval requests</h2><p className="text-sm text-slate-500">Principal review state for actions you submitted.</p><div className="mt-4 space-y-2">{data.recentRequests.length?data.recentRequests.map(r=><div key={r.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{r.requestType.replaceAll('_',' ')}</p><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${r.status==='APPROVED'?'bg-emerald-100 text-emerald-700':r.status==='REJECTED'?'bg-rose-100 text-rose-700':r.status==='REVISION_REQUIRED'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'}`}>{r.status.replaceAll('_',' ')}</span></div>{r.principalRemark&&<p className="mt-2 text-xs text-slate-600"><b>Principal:</b> {r.principalRemark}</p>}<p className="mt-2 text-[11px] text-slate-400">Updated {new Date(r.updatedAt).toLocaleString()}</p></div>):<p className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">You have not submitted any approval requests yet.</p>}</div></article>
   </section>
   <section className="mt-6 rounded-[30px] border border-white bg-white/90 p-6 shadow-xl"><div className="flex items-center gap-3"><CampaignRounded className="text-violet-600"/><div><h2 className="text-xl font-black">Latest Staff announcements</h2><p className="text-sm text-slate-500">Published school notices targeted to Staff.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.announcements.length?data.announcements.map(a=><article key={a.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{a.title}</h3>{a.isPinned&&<span className="rounded-full bg-violet-100 px-2 py-1 text-[10px] font-black text-violet-700">PINNED</span>}</div><p className="mt-2 text-sm text-slate-500">{a.body}</p><p className="mt-3 text-[11px] text-slate-400">{new Date(a.createdAt).toLocaleString()}</p></article>):<p className="text-sm text-slate-500">No Staff announcements.</p>}</div></section>
  </>}
 </section></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <article className="rounded-[24px] border border-white bg-white/90 p-5 shadow-lg transition hover:-translate-y-1"><div className="inline-flex rounded-2xl bg-gradient-to-br from-blue-600 to-violet-500 p-2.5 text-white">{icon}</div><p className="mt-3 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-3xl font-black text-slate-950">{value}</p></article>}
function Quick({to,icon,title,note}:{to:string;icon:React.ReactNode;title:string;note:string}){return <Link to={to} className="rounded-[22px] border border-white bg-white/88 p-4 shadow-lg transition hover:-translate-y-1 hover:shadow-xl"><div className="inline-flex rounded-xl bg-gradient-to-br from-cyan-500 to-blue-600 p-2 text-white">{icon}</div><p className="mt-3 font-black text-slate-900">{title}</p><p className="text-xs text-slate-500">{note}</p></Link>}
